<pre class="metadata">
Title: Solid Application Interoperability
Shortname: your-spec
Level: 1
Max ToC Depth: 2
Status: w3c/ED
Group: w3c
URL: https://solid.github.io/data-interoperability-panel/ecosystem/
Editor: Justin Bingham
Editor: Eric Prud'hommeaux
Editor: Josh Collins
Markup Shorthands: markdown yes
Abstract:
  A proposal for a Solid ecosystem that supports data interoperability across
  applications while enabling secure collaboration and query using intuitive
  data boundaries without changing the fundamentals of Solid, presented in the
  form of an end-to-end use case.
</pre>

<!-- For bikeshed style overrides -->
<style>
table.permissions thead tr {
  font-size: 12px;
}

table.permissions tbody tr:nth-child(even) {
  background-color: lightgray;
  font-size: 10px;
}

table.permissions tbody td {
  font-size: 10px;
}

table.classinfo thead tr th[colspan] {
  text-align: left;
  font-size: 15px;
}

table.classinfo thead tr th {
  text-align: left;
  font-size: 14px;
}

table.classinfo tbody tr:nth-child(odd) {
  background-color: lightgray;
  font-size: 12px;
}

table.classinfo tbody tr td {
  font-size: 12px;
}

table.tree thead tr {
  font-size: 14px;
}

table.tree tbody tr:nth-child(even) {
  background-color: lightgray;
  font-size: 14px;
}

table.tree tbody td {
  font-size: 14px;
}

pre {
  font-size: .8em;
}

figcaption {
  text-align: left;
}

a[data-link-type=dfn] {
  color: #000000;
}

a[href*=".ttl"] {
  color: #339966;
  border-bottom: 1px solid #339966;
}

a[href^="#class"] {
  color: #339966;
  border-bottom: 1px solid #339966;
}

a.vocab {
  color: #339966;
  border-bottom: 1px solid #339966;
}

a[href*=".shex"] {
  color: #cc2900;
  border-bottom: 1px solid #cc2900;
}

a[href^="#shex"] {
  color: #cc2900;
  border-bottom: 1px solid #cc2900;
}

a[href*=".tree"] {
  color: #e68a00;
  border-bottom: 1px solid #e68a00;
}

a[href^="#tree"] {
  color: #e68a00;
  border-bottom: 1px solid #e68a00;
}

em.rfc2119 {
  text-transform: lowercase;
  font-variant: small-caps;
  font-style: normal;
  font-size: 18px;
  color: #900;
}

</style>

<div boilerplate="copyright">
MIT License Copyright 2019 - 2020 W3C Solid Community Group
</div>

Problems and Goals {#problems-goals}
=====================

Solid affords us the opportunity to create a valuable and
powerful ecosystem where people and organizations retain control of their data,
but are also able to put it to work and use it to its full potential. The
fundamentals of Solid make this possible, but further definition of standard
methods and mechanisms must be established to make it practical, intuitive, and
secure.

<div class="assertion">

[Problem #1](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#problem-1---disparate-applications-cannot-practically-interoperate-over-the-same-data-safely-and-effectively) -
    Disparate applications cannot practically interoperate over the same data
    safely and effectively.

* <b>[Goal](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#goal-1---seamless-data-interoperability-across-disparate-applications) -
    Seamless data interoperability across disparate applications.</b>

[Problem #2](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#problem-2---people-must-be-able-to-understand-what-data-they-have-to-effectively-use-it-or-share-it-safely) -
    People must be able to understand what data they have to effectively use it
    or share it safely.

* <b>[Goal](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#goal-2---use-intuitive-data-boundaries-to-provide-human-to-machine-interoperability) -
    Use intuitive data boundaries to provide human to machine interoperability.</b>

[Problem #3](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#problem-3---disparate-entities-using-different-applications-must-be-able-to-safely-and-effectively-interoperate-within-their-scope-of-authorization) -
    Disparate entities using different applications must be able to
    safely and effectively interoperate within their scope of authorization.

* <b>[Goal](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#goal-3---secure-collaboration-over-intuitive-data-boundaries) -
    Secure collaboration over intuitive data boundaries.</b>

[Problem #4](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#problem-4---people-shouldnt-need-to-think-about-how-to-physically-organize-their-data-to-use-solid) -
    People shouldn’t need to think about how to physically organize
    their data to use Solid.

* <b>[Goal](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#goal-4---standard-and-flexible-organizing-model-for-data) -
    Standard and flexible organizing model for data.</b>

[Problem #5](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#problem-5---when-data-is-stored-and-secure-it-should-be-queryable-using-any-mechanism-and-able-to-be-requested-in-different-representations) -
    When data is stored and secure, it should be queryable using any
    mechanism, and able to be requested in different representations.

* <b>[Goal](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#goal-5---flexibility-and-support-for-different-and-evolving-query-mechanisms) -
    Flexibility and support for different and evolving query mechanisms.</b>

[Problem #6](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#problem-6---these-problems-must-be-solvable-using-the-fundamentals-of-solid-as-it-exists-today) -
    These problems must be solvable using the fundamentals of Solid
    as it exists today.

* <b>[Goal](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md#goal-6---optimize-and-extend-but-do-not-change-solid-fundamentals) -
    Optimize and extend, but do not change Solid fundamentals.</b>

</div>

We must be able to support data interoperability across applications while
enabling secure collaboration and query using intuitive data boundaries.

Diversity in how the same data will be accessed and manipulated by different
entities and applications exacerbates the need for reliable mechanisms that
protect against data corruption, data leakage, or broken workflows

Standard methods and mechanisms for interoperability, collaboration, and
security of data in a Solid Pod must realize these needs, and it must be done
without changing the fundamentals of Solid.

Note: See [[PROBLEMS-AND-GOALS]] for a detailed explanation of each discrete
problem.

Proposal {#proposal}
=====================

In this proposal, we aim to address the stated problems and associated goals
by providing straightforward patterns that can be used in concert to realize
an interoperable [=ecosystem=] for [=Solid=]. To aid in understanding,
we include a reference use case that incorporates key elements of the proposal
in context for the reader.

We introduce [=shape trees=] as a fundamental means through which we model,
validate, organize, and authorize data stored in a Solid [=pod=]. Data becomes
durable, interoperable, and available to be retrieved in different
representations or discovered through any query mechanism.

Nowhere in this proposal does an [=agent=] or
[=application=] need to worry about where to store data, or where to find it.
Data is organized and shared using intuitive data boundaries
provided by [=shape trees=], making it easy for Alice, Bob, and their respective
applications to interoperate with each other in a way that they all understand.
In concert with [=acl resources=], this organization scheme facilitates
straightforward compartmentalized access by [=authenticated agents=] and
[=applications=], and allows them to operate using the least amount of
privilege necessary to complete their tasks.


We introduce patterns for [[#appreg|registering applications]], authorizing
access to data, keeping track of access grants, and of remote resources
for which access has been granted to the [=Agent=].
[=trusted agents|Trusted Agents=] perform important actions for the
[=Agent=] with escalated privileges to help her securely
manage her data and make informed, intuitive, and secure decisions.

Most importantly, this proposal can work with Solid as it exists today, on its
own or alongside other conventions, with some caveats.

<div class="assertion">

* Identifying the [=ApplicationID=] in an [=acl resource=] statement
    requires [[WAC]] extension and IdP support. This proposal still works
    without this, but you would no longer be able to compartmentalize
    access between [=user-piloted applications=] in use by the
    [=Agent=].
* This proposal assumes support for [=shape=] validation on the [=Solid=]
    server. It will still work without this support, but will significantly
    hamper data durability, integrity, and interoperability. Similarly,
    it doesn't require the server to perform [=shape tree=] validation,
    but more reliable and durable interoperability would be achieved with
    server-side support.

</div>

Reference Use Case {#usecase}
=====================

In our use case, Alice wants to use a new application to record and manage
her personal and professional notes. She does a Web search and finds
NeverNote (`https://nevernote.example`), a single-page (SPA) web-based
application that advertises itself as *solid enabled*. Alice is excited
about this because she recently created a Solid pod for herself
at `https://alice.pod.example`.

When Alice brings up NeverNote in her
web browser, she is prompted to authenticate with her [=WebID=] because
NeverNote doesn’t know who she is yet, nor is it permitted to send
authenticated requests to her pod.

## Alice registers NeverNote ## {#alice-registers}

Alice logs into her [=identity provider=] (`https://idp.example`) with her
WebID (`https://alice.pod.example/profile/id#me`), and receives
a [=token=] that NeverNote can use to make requests to her pod.
The token identifies her as Alice (`https://alice.pod.example/profile/id#me`),
using NeverNote (`https://nevernote.example/id#agent`).

At this point, NeverNote isn't sure whether Alice is a brand new user of
NeverNote, or an existing user with stored preferences and caches, who has
granted NeverNote access to her notebook and note data.

To determine whether Alice has already registered NeverNote, NeverNote
[[#appreg-lookup|looks for an application registration]] for itself through
Alice's [[#reg]]. If no registration is found, NeverNote will go through
a quick [[#appreg-new|registration process]]. If there is already an
existing registration for NeverNote, no additional
steps are necessary, and NeverNote is able to access the registration entry
subject to the limitations of the [[#appreg-permissions]], in accordance with
the [[#appreg-structure]] of the resource hierarchy.

## Alice grants NeverNote access to data ## {#alice-authorizes}

Issue: Complete Data Registration and Data Authorization and update this
section.

* Through the help of her Authorization Agent, Alice grants NeverNote the
    following privileges:
  * Access to Notes that already existed in her Pod
  * Ability to create new Notes that NeverNote will have permission to manage
  * Ability to create new Notebooks that NeverNote will have permission to manage

## Alice collaborates with Bob ## {#alice-collaborates}

Issue: Complete Collaborative Access then update this section.

* Alice and Bob collaborate on a Notebook in Alice’s Pod. Bob is using a
    different application than NeverNote called OtherNote.


Agent {#ecoagent}
=====================

## Overview ## {#agent-overview}

An [=Agent=] is a distinct individual, group, or piece of
software with an identity that can be strongly authenticated. They are
the primary actors in the Solid [=ecosystem=].

Agents have [=identities=], and dereferencing those identities leads
to [=identity profile documents=] that let other agents and applications
participating in the ecosystem know how to interact with them.

Even the applications that the agent uses directly find their way to
the agent's data through the agent's identity.

Agents are represented by the `eco:Agent` class.

Issue: Expand this text further to demonstrate the association with the
traditional identity profile document when dereferencing a webid, with
data model, structure/validation, and perms.

Registrar {#reg}
=====================

## Overview ## {#registrar-overview}

A [=Registrar=] provides [=Registries=] where an [=Agent=] can register,
store, and lookup essential data needed to participate in the ecosystem.
It supports key functions like application registration,
organizing and tracking data, and more.

* [[#appreg]] uses [=Application Registries=] to manage
    [=Application Registrations=].
* Data Registration relies on data registries to organize,
    store, and find registered data.
* Access registries let agents track and communicate access grants to
    resources they control.
* Agents track and manage data that has been shared with them through
    remote registries.


## Registrar Data Model ## {#reg-model}

<figure>
  <img src="registrar-model.svg" width=100%/>
  <figcaption align="center">Top level registrar data model</figcaption>
</figure>


Humans, software, or device [=Agents=] participating in the Solid ecosystem
are represented by the class [eco:Agent](ecosystem.ttl#Agent). Each
[=Agent=] has a [=Registrar=], represented by the class
[eco:Registrar](ecosystem.ttl#Registrar).

<figure>
  <figcaption>[=Agent=] at https://alice.pod.example/profile/id#me linking to
  [=Registrar=]</figcaption>
  <pre highlight="turtle">
  <#me>
    a eco:Agent;
    eco:hasRegistrar &lt;https://alice.pod.example/registries/#registrar&gt; .
  </pre>
</figure>

A [=Registrar=] links to a number of [=Registry Sets=]. [=Registry Sets=] are
represented by the class [eco:RegistrySet](ecosystem.ttl#RegistrySet).
They are collections of one or more linked [=Registries=]. They are almost
always focused on a single [=Registry=] type, through type-specific
subclasses like
[eco:ApplicationRegistrySet](ecosystem.ttl#ApplicationRegistySet).

A given [=Registrar=] is linked to a [=Registry Set=] via the
[eco:hasRegistrySet](ecosystem.ttl#hasRegistrySet) property, or through
type-specific sub-properties like
[eco:hasApplicationRegistrySet](ecosystem.ttl#hasApplicationRegistrySet).

<figure>
  <figcaption>[=Registrar=] at
  https://alice.pod.example/registries/#registrar linking to
  [=Registry Sets=]</figcaption>
  <pre highlight="turtle">
  <#registrar>
    a eco:Registrar;
    eco:hasApplicationRegistrySet &lt;https://alice.pod.example/registries/application#set&gt; ;
    eco:hasDataRegistrySet &lt;https://alice.pod.example/registries/data#set&gt; .
  </pre>
  </figure>
</figure>

A [=Registry=] is a place where an [=Agent=] can register, store, and lookup
essential data needed to participate in the [=ecosystem=]. It is represented
by the [eco:Registry](ecosystem.ttl#Registry) class.

A given [=Registry Set=] links to any number of [=Registries=] via the
[eco:hasRegistry](ecosystem.ttl#hasRegistry) property.

This applies to type-specific to subclasses as well. For example, an
[=Application Registry Set=] links to any number of [=Application Registries=]
via the same [eco:hasRegistry](ecosystem.ttl#hasRegistry) property.

<figure>
  <figcaption>[=Application Registry Set=] linking to two different
  [=Application Registries=]</figcaption>
  <pre highlight="turtle">
  <#set>
    a eco:ApplicationRegistrySet;
    eco:hasRegistry &lt;https://alice.pod.example/applications/#registry&gt; ,
                    &lt;https://alice.otherpod.example/applications/#registry&gt; .
  </pre>
</figure>

[=Registries=] exist to store and catalog [=Registrations=], each of which
represents an individual unit of information for a given [=Registry=].
[=Registrations=] are represented by the `eco:Registration` class.

A given [=Registry=] links to any number of [=Registrations=] via the
[eco:hasRegistration](ecosystem.ttl#hasRegistration) property.

This applies to type-specific to subclasses as well, which are the normal
mode of use. For example, an
[=Application Registry=] links to any number of [=Application Registrations=]
via the [eco:hasRegistration](ecosystem.ttl#hasRegistration) property.

<figure>
  <figcaption>[=Application Registry=] linking to three
  [=Application Registration=] instances</figcaption>
  <pre highlight="turtle">
  <#registry>
    a eco:ApplicationRegistry ;
    eco:hasRegistration &lt;https://alice.pod.example/applications/02f9d4221d9e5c0ae/#registration&gt ,
                        &lt;https://alice.pod.example/applications/6fe4221d0589d7bde/#registration&gt ,
                        &lt;https://alice.pod.example/applications/543ab04333ba5bcc2/#registration&gt .
  </pre>
</figure>

The properties and associated data of a given [=Registration=]
may vary widely depending on the type of [=Registry=] it is
associated with. However, a number of general properties are inherited from
the base [=Registration=] class
[eco:Registration](ecosystem.ttl#Registration). In the following
example, all properties except for
[eco:registeredApplication](ecosystem.ttl#registeredApplication)
are inherited from
[eco:Registration](ecosystem.ttl#Registration).

<figure>
  <figcaption>An [=Application Registration=] instance</figcaption>
  <pre highlight="turtle" line-highlight="5" line-numbers="true">
  <#registration>
    a eco:ApplicationRegistration ;
    eco:registeredBy &lt;https://alice.pod.example/profile/id#me&gt; ;
    eco:registeredWith &lt;https://trusted.example/ar&gt; ;
    eco:registeredApplication &lt;https://nevernote.example/id#agent&gt; ;
    eco:registeredAt "2020-04-04T20:15:47.000Z"^^xsd:dateTime .
  </pre>
</figure>

## Structure and Validation ## {#reg-structure}

Instances of the classes and properties in the [[#reg-model]]
are organized across different resources and pods for a given [=Agent=]
participating in the [=ecosystem=]. The instance data in resources are
validated by [=shapes=], which are associated with those resources
through [=shape trees=].

<figure>
  <figcaption>Example [=Registrar=] structure for an [=Agent=].
  Excludes some [=Registry=] types for clarity.</figcaption>
  <img src="registrar-tree.svg" width=100%/>
</figure>

The [=Registrar=] linked to an [=Agent=]
is discovered by dereferencing their [=identity=]
(e.g. `https://alice.pod.example/profile/id#me`) to access their
[=identity profile document=], represented in
the figure above as `/id`.

The [=Registrar=] is stored in the RDF graph of the
`/registeries` container at `https://alice.pod.example/registries/#registrar`.
The [=Registrar=] instance links to a collection of type-specific
[=Registry Set=] instances stored in the `/registries` container.

The shape tree [ecot:registrar-tree](ecosystem.tree#registrar-tree)
associated with the `/registries` container
specifies this resource structure. It assigns the
[ecos:RegistrarShape](ecosystem.shex#RegistrarShape) to validate
a [=Registrar=] instance in the graph of the container resource. It also assigns [ecos:ApplicationRegistrySetShape](ecosystem.shex#ApplicationRegistrySetShape)
and [ecos:DataRegistrySetShape](ecosystem.shex#DataRegistrySetShape)
to validate the
[eco:ApplicationRegistrySet](ecosystem.ttl#ApplicationRegistrySet) and
[eco:DataRegistrySet](ecosystem.ttl#DataRegistrySet)
instances in the contained resources.

<figure>
  <figcaption>[=Shape trees=], [=shapes=], and [=Registry Set=] resources
  associated with a [=Registrar=] container</figcaption>
  <img src="registrar-registries.svg" width=100%/>
</figure>

A [=Registry Set=] resource of a specific type will link to one or more
[=Registry=] instances of the same type.

For example, the [=Application Registry Set=] at
`https://alice.pod.example/registries/application#set` links to two
[=Application Registry=] instances, one of them being
`https://alice.pod.example/applications/#registry`.

The [=Application Registry=] instance is stored in the RDF graph
of the `/applications` container at
`https://alice.pod.example/applications/#registry`. It links to a
collection of [=Application Registration=] instances stored in
the `/applications` container.

The shape tree
[ecot:application-registry-tree](ecosystem.tree#application-registry-tree)
associated with the `/applications` container specifies this resource
structure. It assigns the
[ecos:ApplicationRegistryShape](ecosystem.shex#ApplicationRegistryShape)
to validate the [=Application Registry=] instance in the
container resource. It also assigns a
[ecos:ApplicationRegistrationShape](ecosystem.shex#ApplicationRegistrationShape)
to validate an [=Application Registration=] in every
contained resource.

<figure>
  <figcaption>[=Shape trees=], [=shapes=], and [=Application Registration=]
  resources associated with an [=Application Registry=] container</figcaption>
  <img src="registrar-applications.svg" width=100%/>
</figure>

## Permission Model ## {#reg-permissions}

The permission model for the [=Registrar=] resources detailed in [[#reg-structure]]
are illustrated in the table below. That said, the following key points
are worth noting:

* The [=identity profile document=] at `/id` is the only resource that is
    publicly accessible (with read-only privileges).
* The only information exposed is a link to Alice's [=Registrar=] at
    `/registries`, which is a protected document.
* Neither the types or locations of Alice's [=Registries=] are
    ever publicly exposed.

The [=Agent=] should be assumed to
have control-level access across her entire data space.

<figure>
<figcaption>Permission model for [=Registrar=] resources</figcaption>
  <table class="data permissions" align="left">
    <col>
    <colgroup></colgroup>
    <colgroup></colgroup>
    <colgroup span=2></colgroup>
    <colgroup span=2></colgroup>
    <thead>
      <tr>
        <th></th>
        <th scope="colgroup">Controller</th>
        <th scope="colgroup">Public</th>
        <th colspan=2 scope="colgroup">Selectively Trusted</th>
        <th colspan=2 scope="colgroup">Selectively Granted</th>
      </tr>
      <tr>
        <th scope="col">Resource</th>
        <th scope="col">Access</th>
        <th scope="col">Access</th>
        <th scope="col">Subject</th>
        <th scope="col">Access</th>
        <th scope="col">Subject</th>
        <th scope="col">Access</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>`/id`</td>
        <td>Control</td>
        <td>Read</td>
        <td>Identity Agent</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`/registries/`</td>
        <td>Control</td>
        <td>-</td>
        <td>Trusted Agents</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`-- /registries/application`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`-- /registries/data`</td>
        <td>Control</td>
        <td>-</td>
        <td>Data Authorization Agent</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`/applications/`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`-- /applications/registration-123/`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>Registered App.</td>
        <td>Read</td>
      </tr>
      <tr>
        <td>`-- /applications/registration-123/*`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>Registered App.</td>
        <td>Write</td>
      </tr>
      <tr>
        <td>`/data/`</td>
        <td>Control</td>
        <td>-</td>
        <td>Data Authorization Agent</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`-- /data/registration-456/`</td>
        <td>Control</td>
        <td>-</td>
        <td>Data Authorization Agent</td>
        <td>Control</td>
        <td>Grantee</td>
        <td>Varies</td>
      </tr>
      <tr>
        <td>`-- /data/registration-456/*`</td>
        <td>Control</td>
        <td>-</td>
        <td>Data Authorization Agent</td>
        <td>Control</td>
        <td>Grantee</td>
        <td>Varies</td>
      </tr>
    </tbody>
  </table>
</figure>

Application Registration {#appreg}
=====================

## Overview ## {#appreg-overview}

Application Registration gives [=Agents=] participating in the Solid
[=ecosystem=] a way to register and track the [=Applications=] they've elected
to use with their data. It also provides each [=Application=] with a place
to store metadata, preferences, access grants, caches, and other internal
data specific to the function of a given [=Application=].

An [=Application Registry=] for storing individual
[=Application Registrations=] is introduced, implemented through the [[#reg]].

## Data Model ## {#appreg-datamodel}

<figure>
  <img src="appreg-model.svg" width=100%/>
  <figcaption>Data model for application registration</figcaption>
</figure>

Application Registration extends the [[#reg-model]] with type-specific
subclasses and subproperties.

* An [=Agent=] has a [=Registrar=], which links to
    [=Application Registry Set=] instances.

* An [=Application Registry Set=] links to any number of
    [=Application Registry=] instances via the
    [eco:hasRegistry](ecosystem.ttl#hasRegistry) property.

* An [=Application Registry=] links to any number of
    [=Application Registrations=] via the
    [eco:hasRegistration](ecosystem.ttl#hasRegistration) property.

* An [=Application Registration=] extends the
    [eco:Registration](ecosystem.ttl#Registration)
    class with the
    [eco:ApplicationRegistration](ecosystem.ttl#ApplicationRegistration)
    subclass.

The [eco:ApplicationRegistration](ecosystem.ttl#ApplicationRegistration)
subclass also introduces the following properties:

* [eco:registeredApplication](ecosystem.ttl#registeredApplication) -
    [=ApplicationID=] of the [=Application=] that is being registered.

<figure>
  <figcaption>Instance data for
  an [=Application Registration=] at
  https://alice.pod.example/applications/02f9d4221d9e5c0ae/#registration
  </figcaption>
  <pre highlight="turtle" line-highlight="5" line-numbers="true">
  <#registration>
    a eco:ApplicationRegistration ;
    eco:registeredBy &lt;https://alice.pod.example/profile/id#me&gt; ;
    eco:registeredWith &lt;https://trusted.example/ar&gt; ;
    eco:registeredApplication &lt;https://nevernote.example/id#agent&gt; ;
    eco:registeredAt "2020-04-04T20:15:47.000Z"^^xsd:dateTime .
  </pre>
</figure>

## Structure and Validation ## {#appreg-structure}

A given [=Agent=] will have one or more
[=Application Registries=] discoverable through the
[[#reg-model]], via resources that implement
[[#reg-structure|Registrar Structure and Validation]].

<figure>
  <figcaption>An [=Application Registry=] at
  https://alice.pod.example/applications/#registry</figcaption>
  <img src="registrar-applications.svg" width=100%/>
</figure>

The [=Application Registry=] instance data is stored in the RDF graph
of the `/applications` container at
`https://alice.pod.example/applications/#registry`. It links to a
collection of [=Application Registrations=] stored in
the `/applications` container.

The shape tree
[ecot:application-registry-tree](ecosystem.tree#application-registry-tree)
associated with the `/applications` container specifies this resource
structure. It assigns the
[ecos:ApplicationRegistryShape](ecosystem.shex#ApplicationRegistryShape)
to validate the [=Application Registry=] instance data in the
container resource, and says that the container includes instances of
[ecot:application-registration-tree](ecosystem.tree#application-registration-tree),
which any resources added to the `/applications` container must conform to.

Conforming to
[ecot:application-registration-tree](ecosystem.tree#application-registration-tree)
ensures that the container for the [=Application Registry=] at
`/applications#registry` only contains valid [=Application Registrations=].

Specifically:

* Any resource added to the `/applications` container must be a
    container (`st:expectsType st:ShapeTreeContainer`)
* An [=Application Registration=] must be stored in the
    RDF graph of that container, to successfully pass shape validation via
    `st:validatedBy <ecos#ApplicationRegistrationShape>`.

<figure>
  <figcaption>An [=Application Registration=] at
  https://alice.pod.example/applications/02f9d4221d9e5c0ae/#registration
  </figcaption>
  <img src="appregistration-structure.svg" width=100%/>
</figure>

These [=Application Registrations=] are associated with container resources
so that the [=Application=] that has been registered
has dedicated space to store data that is very specific to its internal
functions. In the figure above, we can see an application-specific
configuration resource (`config.ttl`) and a summary index file (`summary.idx`).

### Naming application registration resources ### {#appreg-naming}

In this proposal, resource names for ecosystem instances are almost always
randomly generated. However, when creating an
[ecot:application-registration-tree](ecosystem.tree#application-registration-tree)
for an [=Application Registration=], the container
must be named using a SHA-256 hash encoding of the [=ApplicationID=] for the
[=Application=], which is linked through the
[eco:registeredApplication](ecosystem.ttl#registeredApplication) property.

:: <b>NeverNote ApplicationID:</b> `https://nevernote.example/id#agent`
:: <b>SHA-256 Hash:</b> `70e9249113f8aef095626980e82f13833f24a902571502ef726b4d7e69739ba3`

In our [[#usecase]], the name of the container for NeverNote's
[=Application Registration=] would be
`70e9249113f8aef095626980e82f13833f24a902571502ef726b4d7e69739ba3`.

There is a reasonable argument for whether or not a one-way hash alogorithm
like SHA-256 is appropriate, as we are primarily using it as a mechanism
for URL encoding to create uniform, opaque resource names,
and the ApplicationID for a given [=Application=]
is publicly shared. However, the use of one-way hash does add a modicum
of additional privacy at a miniscule expense.

Issue: Is it appropriate to use a one-way hash for application registration
resource names. [Github issue](https://github.com/solid/data-interoperability-panel/issues/48)

### Use of internal application space ### {#appreg-internal}

There is a legitimate argument that giving [=Applications=] their own
private data space in Solid is counterintuitive to Solid’s proposition to
decouple data and [=Applications=].

However, there are certain types of data that are very specific to
the function of a particular [=Application=], and have no value to other
[=Applications=]. This may include but not be limited to app-specific
preferences, configurations, caches, or indexes. Forcing that data into
[=shape trees=] and [=shapes=] stored in the data registry that are supposed
to be consumable and interoperable by other [=Applications=] can lead to
frankenstein-like [=shape trees=] and [=shapes=] that no one wants to use.
Giving [=Applications=] a private space where they can store internal data
is therefore a key factor in broad interoperability,
because it protects interoperable data from pollution by narrowly
focused elements.

Ultimately, if [=Applications=] don't want to be interoperable, there's
no reasonable convention that could prevent it. For example, they could
decide to use proprietary vocabularies, [=shapes=], and [=shape trees=].
However, there are motivating factors to
be interoperable, because in doing so they become compatible with a
slew of data that already exists in the [=ecosystem=], including data within
their competitive landscape. Providing a private space allows [=Applications=]
to separate some internals from true interoperable data so that the
interoperable data is cleaner and more usable. Our belief is that
this helps avoid the creation of far-reaching app-specific silos.

Because this space is private to an [=Application=] and not meant to
be interoperable, the [=Application=] may or may not decide to utilize
data validation facilities like [=shape trees=] or [=shapes=].

## Permission Model ## {#appreg-permissions}

There is no public access to any data in an [=Application Registry=].

Only [=Agents=] that have been selectively trusted to assist a
given agent with managing application registration have the ability to manage
contents and permissions across [=Application Registries=],
including the creation and modification of [=Application Registrations=].

A given registered [=Application=] has read access to its
[=Application Registration=], and read/write access to
the data space inside its container. It does not get control privileges.

<figure>
<figcaption>Permission model for [=Application Registry=] resources</figcaption>
  <table class="data permissions" align="left">
    <col>
    <colgroup></colgroup>
    <colgroup></colgroup>
    <colgroup span=2></colgroup>
    <colgroup span=2></colgroup>
    <thead>
      <tr>
        <th></th>
        <th scope="colgroup">Controller</th>
        <th scope="colgroup">Public</th>
        <th colspan=2 scope="colgroup">Selectively Trusted</th>
        <th colspan=2 scope="colgroup">Selectively Granted</th>
      </tr>
      <tr>
        <th scope="col">Resource</th>
        <th scope="col">Access</th>
        <th scope="col">Access</th>
        <th scope="col">Subject</th>
        <th scope="col">Access</th>
        <th scope="col">Subject</th>
        <th scope="col">Access</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>`/applications/`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`-- /applications/02f9d4221d9e5c0ae/`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>Registered App.</td>
        <td>Read</td>
      </tr>
      <tr>
        <td>`-- /applications/02f9d4221d9e5c0ae/*`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>Registered App.</td>
        <td>Write</td>
      </tr>
      <tr>
        <td>`-- /applications/6fe4221d0589d7bde/`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>Registered App.</td>
        <td>Read</td>
      </tr>
      <tr>
        <td>`-- /applications/6fe4221d0589d7bde/*`</td>
        <td>Control</td>
        <td>-</td>
        <td>App. Registration Agent</td>
        <td>Control</td>
        <td>Registered App.</td>
        <td>Write</td>
      </tr>
    </tbody>
  </table>
</figure>

## Looking up an Application Registration ## {#appreg-lookup}

There are a few reasons that different actors might lookup
an [=Application Registration=]:

* The [=Agent=] may want to view or manage their collection of registered
    [=Applications=].
* Another [=trusted agent=] may assist the [=Agent=] with management
    and registration of [=Applications=].
* An [=Application=] may want to see if it has been registered,
    and access its [=Application Registration=]
    if it exists. *This is the most frequently occuring scenario.*

Per the [[#appreg-permissions]], the [=Agent=] and
any [=trusted agents=] for application registration will have access and
visibility across [=Application Registries=] and
[=Application Registrations=]. An
[=Application=] will only have access to its own [=Application Registration=],
in which case it would be linked to that [=Application Registration=] via the
[eco:registeredApplication](ecosystem.ttl#registeredApplication) property.

Since [=Applications=] do not have access to the list of [=Applications=]
in [=Application Registries=], the only way they can check to see if they
are registered is to perform a direct lookup in the addressable space
of each [=Application Registry=] in the [=Application Registry Set=],
using the SHA-256 hash of its [=applicationID=].

<pre>
GET https://alice.pod.example/applications/70e9249113f8aef095626980e82f13833f24a902571502ef726b4d7e69739ba3
</pre>

Inability to access the [=Application Registration=] would be a result of:

* There is no [=Application Registration=] for that
    [=Application=] in the [=Application Registry=].
* There is an [=Application Registration=] at the target URL, but
    it cannot be accessed because it associated with a
    different [=Application=].

In either case, the server may return either a 403 or 404 depending on
server or user privacy preference.

If an [=Application=] can access the
[=Application Registration=], then it can confirm that it
is already a registered [=Application=] for the [=Agent=].

If an [=Application=] is not registered, and would like to be,
it will need to go through the process of [[#appreg-new]].

## Registering an Application ## {#appreg-new}

In almost every case, an [=Application=] will not be permitted
to register itself, and will need the
assistance of a [=trusted agent=] that has been authorized to assist
with application registration for a given [=Agent=].

Issue: Agents that can perform these capabilities will be discoverable
through the registrar. Until that section is written, we'll use a
hard-coded properties associated with the Agent for discovery.

The [=Application=] will look for another
[=Application=] that is linked with the [=Agent=] through the
[eco:trustsForApplicationRegistration](ecosystem.ttl#trustsForApplicationRegistration)
property.

<figure>
  <figcaption>[=Agent=] at https://alice.pod.example/profile/id#me linking to Application
  Registration Agent</figcaption>
  <pre highlight="turtle">
    <#me>
      a eco:Agent;
      eco:trustsForApplicationRegistration &lt;https://trusted.example/ar/&gt; .
  </pre>
</figure>

The [=Application=] will redirect the [=Agent=] via the
synchronous [[#trusted|trusted agent]] pattern to the [=Application=] linked by
[eco:trustsForApplicationRegistration](ecosystem.ttl#trustsForApplicationRegistration),
supplying its [=ApplicationID=] as a parameter.

The [=application registration agent=] is now expected to dereference
(i.e. perform an HTTP GET on) the [=ApplicationID=] to retrieve an
[=application profile document=]. The contents of that document
help the [=Agent=] determine whether that [=Application=] is suitable for
approval.

For example, verification of a verifiable credential
stored in the [=application profile document=], issued by a trusted third party,
is a good indicator of the [=Application’s=] trustworthiness.
Similarly, an [=Application=], or the [=identity provider=] it uses, may
be listed on a trusted whitelist that the [=trusted agent=]
consults. It is able to raise issues related to these checks (or others)
to the [=Agent=] as part of her decision making process.

Assuming suitability and confirmation from the [=Agent=], the
[=application registration agent=] will proceed to create the
[=Application Registration=] for
the [=Application=] in the appropriate [=Application Registry=].
When it is finished, it will return her to
the [=Application=] at the
[eco:applicationRegistrationCallback](ecosystem.ttl#applicationRegistrationCallback)
provided in the application profile document.

### Creating the application registration entry ### {#appreg-creating}

The [=application registration agent=] is responsible for creating
the [=Application Registration=] in conformance with the
documented [[#appreg-structure]] pattern.

Specifically, the
[ecot:application-registration-tree](ecosystem.tree#application-registration-tree)
stipulates that the [=Application Registration=] be a container via
`st:expectsType st:ShapeTreeContainer`.

The [=Application Registration=] must be added to the RDF
graph of that container with a `<#registration>` subject, and pass validation
against the
[ecos:ApplicationRegistrationShape](ecosystem.shex#ApplicationRegistrationShape).

The [=Application Registration's=] properties must be set as follows:

* [eco:registeredBy](ecosystem.ttl#registeredBy): linked to the [=identity=]
    of the [=authenticated agent=] that invoked the registration
    (i.e. the [=webid=] of the [=Agent=])
* [eco:registeredWith](ecosystem.ttl#registeredWith): linked to the
    [=ApplicationID=] of the [=trusted agent=] that facilitated the
    registration, typically the [=application registration agent=].
* [eco:registeredApplication](ecosystem.ttl#registeredApplication): linked to
    the [=ApplicationID=] of the [=Application=] that is being registered.
* [eco:registeredAt](ecosystem.ttl#registeredAt): the `xsd:dateTime` of
    the registration.

<figure>
  <figcaption>Example [=Application Registration=]</figcaption>
  <pre highlight="turtle">
  <#registration>
    a eco:applicationRegistration ;
    eco:registeredBy &lt;https://alice.pod.example/profile/id#me&gt; ;
    eco:registeredWith &lt;https://trusted.example/ar&gt; ;
    eco:registeredApplication &lt;https://nevernote.example/id#agent&gt; ;
    eco:registeredAt "2020-04-04T20:15:47.000Z"^^xsd:dateTime .
  </pre>
</figure>

The [=Application Registration=] container must be named in
accordance with the instructions in [[#appreg-naming]].

The [=Application Registration=] container must be added as a child
member of the [=Application Registry=] container.

Access to the [=Application Registration=] must be set per the
instructions in [[#appreg-permissions]].

The [=Application Registration=] must be associated with the
[=Application Registry=] through the
[eco:hasRegistry](ecosystem.ttl#hasRegistry) property in
the graph of the [=Application Registry=].

Data Registration {#datareg}
=====================

## Overview ## {#datareg-overview}

Data Registration gives [=Agents=] participating in the Solid [=ecosystem=]
a way to register, organize, and subsequently manage the data they control.

A [=Data Registry=] for storing individual [=Data Registrations=] is
introduced, implemented through the [[#reg]].

A given [=Data Registry=] provides a specific location in a Solid [=pod=] where
data of various types is organized and stored in a uniform way to aid
authorization, interoperability, discovery, and more. It avoids complex
hierarchies of data that hinder flexibility and interoperability by
employing a relatively flat hierarchy. This creates natural data boundaries
that make data authorization, amongst other things, extremely intuitive.

A [=Data Registry=] can be used for basic discovery, but it is not
designed nor intended to be an efficient means to query or index data.
However, it is *intended* to be used as reliable source data for different
query engines or indexing schemes.

## Data Model ## {#datareg-model}

<figure id="fig-datareg-model">
  <img src="datareg-model.svg" width=100%/>
  <figcaption>Data model for data registration</figcaption>
</figure>

Data Registration extends the [[#reg-model]] with type-specific subclasses
and subproperties.

An [=Agent=] has a [=Registrar=] that links to [=Data Registry Sets=]
via the [eco:hasDataRegistrySet](ecosystem.ttl#hasDataRegistrySet) property.

A [=Data Registry Set=] links to any number of [=Data Registries=] via
the [eco:hasRegistry](ecosystem.ttl#hasRegistry) property.

A [=Data Registry=] links to any number of [=Data Registrations=]
via the [eco:hasRegistration](ecosystem.ttl#hasRegistration) property.

<figure id="fig-datareg-registrar">
  <figcaption>A [=Registrar=] at https://alice.pod.example/registries/#registrar
  linking to a [=Data Registry Set=]</figcaption>
  <pre highlight="turtle">
  <#registrar>
    a eco:Registrar;
    eco:hasDataRegistrySet &lt;https://alice.pod.example/registries/data#set&gt; .
  </pre>
  </figure>
</figure>


<figure id ="fig-datareg-registry-set">
   <figcaption>A [=Data Registry Set=] at
   https://alice.pod.example/registries/data#set linking to two different
  [=Data Registries=]</figcaption>
  <pre highlight="turtle">
  <#set>
    a eco:DataRegistrySet;
    eco:hasRegistry &lt;https://alice.pod.example/data/#registry&gt; ,
                    &lt;https://alice.otherpod.example/data/#registry&gt; .
  </pre>
</figure>

<figure id="fig-datareg-registry">
  <figcaption>A [=Data Registry=] at https://alice.pod.example/data/#registry
  linking to several [=Data Registrations=]</figcaption>
  <pre highlight="turtle">
  <#registry>
    a eco:DataRegistry ;
    eco:hasRegistration &lt;49a4057a-6ade-4a9d-9869-085a00925259/#registration&gt ,
                        &lt;cf2d40d3-858e-42f7-8b11-d021b5989ed2/#registration&gt ,
                        &lt;628a7371-3a9b-49f9-a7aa-2e9c93e0150b/#registration&gt .
  </pre>
</figure>

A [=Data Registration=] extends the
[eco:Registration](ecosystem.ttl#Registration) class with the
[eco:DataRegistration](ecosystem.ttl#DataRegistration) subclass.

A [=Data Registration=] includes any number of [=Registered Data Instances=]
via the
[eco:hasRegisteredDataInstance](ecosystem.ttl#hasRegisteredDataInstance)
property.

The [eco:DataRegistration](ecosystem.ttl#DataRegistration) subclass
extends the [eco:Registration](ecosystem.ttl#Registration) class with
the following properties:

* [eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree) - URI of the
    [=shape tree=] that is being registered.
* [eco:hasRegisteredDataInstance](ecosystem.ttl#hasRegisteredDataInstance) -
    Any number of [=Registered Data Instances=] of the
    [=shape tree=] associated via
    [eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree).


<figure id="fig-datareg-registration">
  <figcaption>A [=Data Registration=] at
  https://alice.pod.example/data/49a4057a-6ade-4a9d-9869-085a00925259/#registration
  linking to several [=Registered Data Instances=]</figcaption>
  <pre highlight="turtle" line-highlight="5" line-numbers="true">
  <#registration>
    a eco:DataRegistration ;
    eco:registeredBy &lt;https://alice.pod.example/profile/id#me&gt; ;
    eco:registeredWith &lt;https://app.example/id#agent&gt; ;
    eco:registeredAt "2020-04-04T20:15:47.000Z"^^xsd:dateTime .
    eco:registeredShapeTree &lt;https://tree.example/commonnote#notebook-tree&gt; ;
    eco:hasRegisteredDataInstance &lt;3f56c32e-96c6-4b0c-b941-eadc2bf98b18/#notebook&gt; ,
                                  &lt;16e1eae9-20a5-489d-8380-8c07ca3805c4/#notebook&gt; ,
                                  &lt;886785d2-6c23-46ee-9e19-5ac36b7bcd71/#notebook&gt; ,
                                  &lt;dae5015c-d5f9-4ede-b9eb-7ca7a19854a9/#notebook&gt; .
    </pre>
</figure>

## Structure and Validation ## {#datareg-structure}

The resources associated with an [=Agent's=] [=Data Registries=] conform
to and extend the general patterns detailed in Registrar [[#reg-structure]].

Consequently, this section focuses on the unique composition and validation of
[=Data Registrations=] in a [=Data Registry=], and the
[=Registered Data Instances=] contained in each [=Data Registration=].

### Structure of Data Registrations in a Data Registry ### {#datareg-registrations-structure}

<figure id="fig-datareg-registry-structure">
  <figcaption>A [=Data Registry=] at
  https://alice.pod.example/data/#registry</figcaption>
  <img src="datareg-structure.svg" width=100%/>
</figure>

In the figure above, a [=Data Registry=] instance is stored in the RDF graph
of the `https://alice.pod.example/data/` container at `https://alice.pod.example/data/#registry`. This
[=Data Registry=] contains a set of [=Data Registrations=] (all stored in
the `https://alice.pod.example/data/` container), [as shown](#fig-datareg-registry) in the
previous section.

Each individual [=Data Registration=] is associated with one
[=shape tree=], indicated by the
[eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree) property.

<figure id="fig-datareg-registry-tree">
  <figcaption>Definition of an
  [ecot:data-registry-tree](ecosystem.tree#data-registry-tree)</figcaption>
  <pre highlight="turtle">
  <#data-registry-tree>
    a st:ShapeTree ;
    st:expectsType st:ShapeTreeContainer ;
    st:validatedBy &lt;ecos#DataRegistryShape&gt; ;
    st:contains &lt;#data-registration-tree&gt; ,
                  st:AllowNone .
  </pre>
</figure>

The [ecot:data-registry-tree](ecosystem.tree#data-registry-tree)
defines the resource structure for the [=Data Registry=], and the data
validation rules for the resources inside it.

* It assigns the
    [ecos:DataRegistryShape](ecosystem.shex#DataRegistryShape)
    to validate the [=Data Registry=] instance itself, stored in the
    graph of the container resource, [as shown](#fig-datareg-registry) in the
    previous section
* It says that the container includes instances of
    [ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
* It says through `st:AllowNone` that any resources that do not conform to
    [ecot:data-registration-tree](ecosystem.tree#data-registration-tree) are
    not allowed. This container can *only* contain resources that conform to
    [ecot:data-registration-tree](ecosystem.tree#data-registration-tree).

<figure id="fig-datareg-registration-tree">
  <figcaption>Definition of an
  [ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
  </figcaption>
  <pre highlight="turtle">
  <#data-registration-tree>
    a st:ShapeTree ;
    st:expectsType st:ShapeTreeContainer ;
    st:validatedBy &lt;ecos#DataRegistrationShape&gt; ;
    st:matchesUriTemplate "{id}" .
  </pre>
</figure>

Conforming to
[ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
ensures that the [=Data Registry=] container at
`https://alice.pod.example/data/#registry` only contains valid
[=Data Registrations=].

* Any resource added to the `https://alice.pod.example/data/` container must be
    a container per `st:expectsType st:ShapeTreeContainer`.
* It assigns the
    [ecos:DataRegistrationShape](ecosystem.shex#DataRegistrationShape)
    to ensure there is a valid [=Data Registration=] instance in the
    container resource graph.

### Structure of Registered Data Instances in a Data Registration ### {#datareg-instances-structure}

A given [=Data Registration=] will contain any number of
[=Registered Data Instances=] of the [=shape tree=] associated
via [eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree).

Two complementary [=shape trees=] must be assigned to the same
[=Data Registration=] to ensure:

1. It is a well-formed [=Data Registration=]
2. The [=Data Registration=] only contains [=Registered Data Instances=]
    of [eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree).

<figure>
  <figcaption>A [=Data Registration=] at
  https://alice.pod.example/data/49a4057a-6ade-4a9d-9869-085a00925259/#registration
  </figcaption>
  <img src="dataregistration-structure.svg" width=100%/>
</figure>

In the figure above, we can observe the combination of the
[ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
and the [note:note-container-tree](note.tree#note-container-tree) on the
same [=Data Registration=] at
`https://alice.pod.example/data/49a4057a-6ade-4a9d-9869-085a00925259/#registration`.

A [=Data Registration=] can't know which specific
[=shape tree=] will be registered in advance, so the
[ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
can't specify the expected contents of the container with `st:contains`.

However, it is crucial that the contents of the [=Data Registration=] container
be conformant instances of the [=shape tree=] specified in the
[eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree)
property of the [=Data Registration=].

A second [=shape tree=]
([note:note-container-tree](note.tree#note-container-tree) in the example above)
is associated with the [=Data Registration=] to ensure that what is stored
in the container are conformant instances of the
[eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree).

### Naming Registrations and Registered Data Instances ### {#datareg-naming}

The name of the [=Data Registration=] container resource MUST be a
generated \[UUID](https://www.ietf.org/rfc/rfc4122.txt).

The name of a [=Registered Data Instance=] resource linked to a
[=Data Registration=] through
[eco:hasRegisteredDataInstance](ecosystem.ttl#hasRegisteredDataInstance)
MUST be a generated \[UUID](https://www.ietf.org/rfc/rfc4122.txt).

## Permission Model ## {#datareg-permissions}

Almost all of the collaborative use cases between [=Agents=]
in the [=ecosystem=] are based on data furnished through the
[=Data Registry=].

[=Agents=] grant different levels of access to other [=Agents=] on a
case-by-case basis through [[#authz]]. Consequently, a signficant amount
of flexibility is needed in permissioning [=Data Registrations=] and
[=Registered Data Instances=], while at the same time avoiding permission
swamps that become unwieldy to manage.

<figure>
<figcaption>Permission model for [=Data Registry=] resources</figcaption>
  <table class="data permissions" align="left">
    <col>
    <col>
    <colgroup></colgroup>
    <colgroup></colgroup>
    <colgroup span=2></colgroup>
    <colgroup span=2></colgroup>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th scope="colgroup">Controller</th>
        <th scope="colgroup">Public</th>
        <th colspan=2 scope="colgroup">Selectively Trusted</th>
        <th colspan=2 scope="colgroup">Selectively Granted</th>
      </tr>
      <tr>
        <th scope="col">Resource</th>
        <th scope="col">Type</th>
        <th scope="col">Access</th>
        <th scope="col">Access</th>
        <th scope="col">Subject</th>
        <th scope="col">Access</th>
        <th scope="col">Subject</th>
        <th scope="col">Access</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>`/data/`</td>
        <td>[=Data Registry=]</td>
        <td>Control</td>
        <td>-</td>
        <td>Authorization Agent</td>
        <td>Control</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>`-- /49a4057a...5259/`</td>
        <td>[=Data Registration=]</td>
        <td>Control</td>
        <td>Varies</td>
        <td>Authorization Agent</td>
        <td>Control</td>
        <td>Grantee</td>
        <td>Varies</td>
      </tr>
      <tr>
        <td>`---- /168997f0...276a/`</td>
        <td>[=Registered Data Instance=]</td>
        <td>Control</td>
        <td>Varies</td>
        <td>Authorization Agent</td>
        <td>Control</td>
        <td>Grantee</td>
        <td>Varies</td>
      </tr>
    </tbody>
  </table>
</figure>

### Access Scopes for Data Registrations ### {#datareg-scopes}

An [=Agent=] specifies the [=Data Registrations=] and
[=Registered Data Instances=] within them that other
[=Agents=] and/or [=Applications=] can access, as well as what that mode
of access will be.

It is imperative that the permission model enable patterns that
allow the [=Agent=] to make intuitive decisions, without
having to directly manipulate [=acl resources=] for individual documents
and containers throughout the [=Data Registry=].

There are two levels of access that must be considered for a given
[=Data Registration=]:

* **All Instances** - Applies to all existing and yet to be created
      [=Registered Data Instances=] within that [=Data Registration=].
* **Specific Instance** - Applies only to specific
      [=Registered Data Instances=] within that [=Data Registration=].

#### Permissions for All Registered Data Instances #### {#datareg-all}

The [=access modes=] listed in the table below can be combined as needed and
granted to a given [=Authorization Subject=].

Issue: WAC doesn't have any mechanism to extend inherited permissions. The
presence of a specific ACL on a resource negates all inherited permissions,
making it impossible to “slightly adjust” or “modify” a resource
while maintaining the permissions inherited for it.

<figure>
<figcaption>Modes of access for a [=Data Registration=]</figcaption>
  <table class="data" align="left">
    <col>
    <col>
    <thead>
      <tr>
        <th scope="col">Mode</th>
        <th scope="col">Resultant Access</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Read</th>
        <td>Can read all existing and yet to be created
            [=Registered Data Instances=]. Includes being able to see the full
            list of [=Registered Data Instances=] in the registration.</td>
      </tr>
      <tr>
        <th scope="row">Write</th>
        <td>Can modify the [=Data Registration=], and all existing
            [=Registered Data Instances=] within it.
            Can create new [=Registered Data Instances=],
            and can delete them.</td>
      </tr>
      <tr>
        <th scope="row">Control</th>
        <td>Can change permissions on the [=Data Registration=], as well
            as any [=Registered Data Instances=] within it.</td>
      </tr>
      <tr>
        <th scope="row">Append</th>
        <td>Can only create new [=Registered Data Instances=] within the
            [=Data Registration=].</td>
      </tr>
      <tr>
        <th scope="row">Created Resource Permissions</th>
        <td>These determine the permissions assigned to
        [=Registered Data Instances=] created by the [=Authorization Subject=],
        when that [=Authorization Subject=] has been granted Write or Append
        [=access modes=].</td>
      </tr>
    </tbody>
  </table>
</figure>

Issue: Identify the scheme through which created resource permissions are
derived if they are not specified explicitly.

Note: Given the current limitations of [[WAC]], specifically the inability
to extend inherited permissions, it is likely that managing permissions
across all [=Registered Data Instances=] of a [=Data Registrations=] will need
to be managed directly in [[#datareg-specific]], rather than inheriting
from the [=Data Registration=].

#### Permissions for a Specific Registered Data Instance #### {#datareg-specific}

The [=access modes=] listed in the table below can be combined as needed and
granted to a given [=Authorization Subject=] for a specific
[=Registered Data Instance=].

<figure>
<figcaption>Modes of access for a Specific
[=Registered Data Instance=]</figcaption>
  <table class="data" align="left">
    <col>
    <col>
    <thead>
      <tr>
        <th scope="col">Mode</th>
        <th scope="col">Resultant Access</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Read</th>
        <td>Can list and read all resources within the
        [=Registered Data Instance=].</td>
      </tr>
      <tr>
        <th scope="row">Write</th>
        <td>Can modify the [=Registered Data Instance=] and any resources
            within it, including creating and deleting resources.</td>
      </tr>
      <tr>
        <th scope="row">Control</th>
        <td>Can change permissions on the [=Registered Data Instance=]
            and any resources within it.</td>
      </tr>
      <tr>
        <th scope="row">Append</th>
        <td>Can create resources within the [=Registered Data Instance=].
            Can add to a resource in the [=Registered Data Instance=] but cannot
            remove anything from it, or delete it.</td>
      </tr>
      <tr>
        <th scope="row">Created Resource Permissions</th>
        <td>These determine the permissions assigned to
        resources within the [=Registered Data Instance=] created by the
        [=Authorization Subject=], when that [=Authorization Subject=] has
        been granted Write or Append [=access modes=].</td>
      </tr>
    </tbody>
  </table>
</figure>

## Registering Data ## {#datareg-registrations}

Registering data in a [=Data Registry=] is primarily concerned with the
following two operations:

* Registering new *data types* as [=Data Registrations=]
* Storing and registering new *instances of those data types* as
    [=Registered Data Instances=]

This section explains the mechanics of those operations.

Note: Managing [=Data Registrations=] and the [=Registered Data Instances=]
contained within them is inextricably linked to permissioning the data
for effective use and secure collaboration. This is covered at length
in [[#authz]].

### Enlisting the help of a trusted agent ### {#datareg-trustedagent}

In almost every case, an [=Application=] will not be trusted to manage
[=Data Registries=], and will need the assistance of a [=trusted agent=]
that has been authorized to assist with data registration for a given [=Agent=].

Untrusted [=Applications=] can enlist the help of the
[=Data Authorization Agent=]
to assist with privileged operations like registering new
[=Data Registrations=] and changing permissions.

The [=Data Authorization Agent=] trusted by a given [=Agent=] is linked
with them through the
[eco:trustsForDataAuthorization](ecosystem.ttl#trustsForDataAuthorization)
property.

<figure>
  <figcaption>[=Agent=] at https://alice.pod.example/profile/id#me linking to Data
  Authorization Agent</figcaption>
  <pre highlight="turtle">
    <#me>
      a eco:Agent;
      eco:trustsForDataAuthorization &lt;https://trusted.example/da/&gt; .
  </pre>
</figure>

An untrusted [=Application=] must work through the trusted
[=Data Authorization Agent=] anytime that [=Data Registrations=] need to be
managed or additional access is needed to the [=Agent's=] data.

Issue: Patterns to interface with Trusted Agents will be detailed
in the Trusted Agents section.

### Creating the data registration entry ### {#datareg-creating}

[=Data Registrations=] must be created in conformance with the
documented [[#datareg-structure]] pattern.

The [ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
must be assigned to the [=Data Registration=] resource.

<figure id="fig-datareg-create-registration-tree">
  <figcaption>Definition of an
  [ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
  </figcaption>
  <pre highlight="turtle">
  <#data-registration-tree>
    a st:ShapeTree ;
    st:expectsType st:ShapeTreeContainer ;
    st:validatedBy &lt;ecos#DataRegistrationShape&gt; ;
    st:matchesUriTemplate "{id}" .
  </pre>
</figure>

The [ecot:data-registration-tree](ecosystem.tree#data-registration-tree)
stipulates the following:

1. The [=Data Registration=] resource must be a container per
    `st:expectsType st:ShapeTreeContainer`.
1. The [=Data Registration=] instance data must be added to the RDF
    graph of that container, and validate successfully
    against the
    [ecos:DataRegistrationShape](ecosystem.shex#DataRegistrationShape).
1.  The [=Data Registration's=] properties must be set as follows:
    * [eco:registeredBy](ecosystem.ttl#registeredBy): linked to the [=identity=]
        of the [=authenticated agent=] that invoked the registration
        (i.e. the [=webid=] of the [=Agent=])
    * [eco:registeredWith](ecosystem.ttl#registeredWith): linked to the
        [=ApplicationID=] of the [=trusted agent=] that facilitated the
        registration, typically the [=data authorization agent=].
    * [eco:registeredAt](ecosystem.ttl#registeredAt): the `xsd:dateTime` of
        the registration.
    * [eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree): URI of the
        [=shape tree=] that is being registered.

The [=shape tree=] associated with the [=Data Registration=] via
[eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree)
must also be assigned to [=Data Registration=] resource,
per the instructions in [[#datareg-structure]]. This ensures that only
instances of that particular shape tree are added to the container.

The [eco:hasRegisteredDataInstance](ecosystem.ttl#hasRegisteredDataInstance)
property is not populated until the first [=Registered Data Instance=] is
added to the [=Data Registration=].

The [=Data Registration=] container must be named in
accordance with the instructions in [[#datareg-naming]].

The [=Data Registration=] container must be added as a child
member of the [=Data Registry=] container.

Access to the [=Data Registration=] must be set per the
instructions in [[#datareg-permissions]].

The [=Data Registration=] must be associated with the
[=Data Registry=] through the
[eco:hasRegistry](ecosystem.ttl#hasRegistry) property in
the graph of the [=Data Registry=].


### Creating registered data instances ### {#datareg-instances}

Creation of [=Registered Data Instances=] is a matter of storing instance
resources in conformance with the
[eco:registeredShapeTree](ecosystem.ttl#registeredShapeTree).

Each new [=Registered Data Instance=] must be linked to the
[=Data Registration=] via
[eco:hasRegisteredDataInstance](ecosystem.ttl#hasRegisteredDataInstance).

Data Authorization {#authz}
=====================

## Overview ## {#authz-overview}

The ability for one [=Agent=] to grant others access to data in their control
is a fundamental element of a collaborative interoperable ecosystem.

Data Authorization represents of several key elements that
work together to grant, adjust, and rescind access to data controlled by
by an ecosystem participant.

* A common way to express [[#needs]] allows [=ecosystem=] participants to
    convey the types or specific instances of data they require.

* [[#access]] record access decisions made an [=Agent=] on the data in their
    control.

* [[#exchanging]] provides different mechanisms for conveying [[#needs]]
    and [[#access]].

Access Needs {#needs}
=====================

## Overview ## {#needs-overview}

[=Agents=] or [=Applications=] in the [=ecosystem=] often require access to
data controlled by some other [=Agent=]. Consequently, a common way to explain
and communicate data needs between participants in the [=ecosystem=] is
required.

A given [=Agent=] or [=Application=] expresses their access needs by
providing one or more [=Access Need Groups=] to the [=Agent=] controlling
the data they require access to. The channels through which these may be
communicated are detailed in [[#exchanging]].

The [[#prepare-group]] operation processes each [=Access Need Group=]
received by the controlling [=Agent=]. A [=Prepared Access Need Group=] is
generated for each [=Access Need Group=] that was received.

[=Prepared Access Need Groups=] and the [=Prepared Access Needs=] associated
with them are used as input to key
[[#access-operations|Access Grant Operations]], and are stored
as part of the [=Access Grant=].

## Data Model ## {#needs-datamodel}

### Summary ### {#needs-datamodel-summary}

An [=Access Need Group=] links to one or more [=Root Access Needs=] via the
[hasAccessNeed](#classAccessNeedGroup) property. It links to one or more
[=Access Need Overrides=] to influence the defaults inherited when following
a [=Root Access Need=] in the [[#prepare-group]] operation.

An [=Access Need=] is associated with one [=shape tree=] via
[eco:registeredShapeTree](#classAccessNeed).

A [=Prepared Access Need Group=] is linked to the [=Access Need Group=] it
was generated from via [eco:fromAccessNeedGroup](#classPreparedAccessNeedGroup).
It links to an [=Access Need Group Decorator=] via
[eco:hasAccessNeedGroupDecorator](#classPreparedAccessNeedGroup).

It links to one or more [=Root Prepared Access Needs=] via
[eco:hasPreparedAccessNeed](#classPreparedAccessNeed). Each
[=Root Prepared Access Need=] represents
a hierarchy of [=Prepared Access Needs=] corresponding with the associated
[=shape tree=].

Each [=Prepared Access Need=] links to child
[=Prepared Access Needs=] via
[eco:referencesPreparedAccessNeed](#classPreparedAccessNeed) or
[skos:narrower](#classPreparedAccessNeed).

An [=Access Need Group=] links to an [=Access Decorator Index=] of
different [=Access Decorator Series=] that explain the [=Access Need Group=]
and [=Access Needs=] in different languages. Each [=Access Decorator Series=]
has one or more [=Access Decorator Versions=] pointing to an
[=Access Decorator Resource=], which contains the actual language-specific
content mappings.



<figure id="fig-access-need-group">
  <figcaption>An [=Access Need Group=] linking to [=Access Needs=]</figcaption>
  <pre highlight="turtle">
  <#notebook-collaboration-group>
    a eco:AccessNeedGroup ;
    eco:accessNecessity eco:AccessRequired ;
    eco:authenticatesAs eco:Pilot ;
    eco:hasAccessNeed &lt;#notebook&gt; ;
    eco:hasAccessNeedOverride &lt;#note&gt; ;
    eco:hasAccessDecoratorIndex &lt;notebook-access-decorator-index.ttl&gt; .

  <#notebook>
      a eco:AccessNeed ;
      eco:inAccessNeedGroup &lt;#notebook-collaboration-group&gt; ;
      eco:registeredShapeTree &lt;note:notebook-tree&gt; ;
      eco:recursivelyAuthorize true ;
      eco:accessNecessity eco:AccessRequired ;
      eco:accessMode acl:Read, acl:Write .

  <#note> # Override to stop recursion
      a eco:AccessNeed ;
      eco:inAccessNeedGroup &lt;#notebook-collaboration-group&gt; ;
      eco:registeredShapeTree &lt;note:notebook-tree&gt; ;
      eco:recursivelyAuthorize false ;
      eco:accessNecessity eco:AccessRequired ;
      eco:accessMode acl:Read, acl:Write .
  </pre>
</figure>

<figure id="fig-prepared-access-need-group">
  <figcaption>A [=Prepared Access Need Group=] linking to
  [=Prepared Access Needs=]</figcaption>
  <pre highlight="turtle">
  <#prepared-notebook-collaboration-group>
    a eco:PreparedAccessNeedGroup ;
    eco:fromAccessNeedGroup <#notebook-collaboration-group> ;
    eco:hasAccessNeedGroupDecorator ex:notebook-collaboration-decorator ;
    eco:authenticatesAs eco:Pilot ;
    eco:accessNecessity eco:AccessRequired ;
    eco:hasPreparedAccessNeed &lt;#notebook&gt; .

  <#prepared-notebook>
    a eco:PreparedAccessNeed ;
    eco:inPreparedAccessNeedGroup &lt;#prepared-notebook-collaboration-group&gt; ;
    eco:registeredShapeTree note:notebook-tree ;
    eco:hasShapeTreeDecorator note:notebook-decorator&gt; ;
    eco:hasAccessNeedDecorator ex:notebook-need-decorator ;
    eco:accessNecessity eco:AccessRequired ;
    eco:accessMode acl:Read, acl:Write ;
    eco:referencesPreparedAccessNeed <#prepared-note> .

  <#prepared-note>
    a eco:PreparedAccessNeed ;
    eco:inPreparedAccessNeedGroup &lt;#prepared-notebook-collaboration-group&gt; ;
    eco:registeredShapeTree &lt;note:note-tree&gt; ;
    eco:hasShapeTreeDecorator note:note-decorator&gt; ;
    eco:hasAccessNeedDecorator ex:note-need-decorator ;
    eco:accessNecessity eco:AccessRequired ;
    eco:accessMode acl:Read, acl:Write .
  </pre>
</figure>

<figure id="fig-access-need-decorator-index">
  <figcaption>[=Access Decorator Index=] document linked by the
  [#notebook-collaboration-group](#fig-access-need-group)</figcaption>
  <pre highlight="turtle">
  @prefix eco: &lt;http://www.w3.org/ns/solid/ecosystem#&gt; .
  @prefix xsd: &lt;http://www.w3.org/2001/XMLSchema#&gt; .

  <>
    a eco:AccessDecoratorIndex ;
    eco:defaultLanguage "en"^^xsd:language ;
    eco:hasSeries &lt;#series-en&gt; .

  <#series-en>
      a eco:AccessDecoratorSeries ;
      eco:usesLanguage "en"^^xsd:language ;
      eco:hasVersion &lt;#en-v10&gt;, &lt;#en-v11&gt; .

  <#en-v10>
      a eco:AccessDecoratorVersion ;
      eco:isVersion "1.0.0" ;
      eco:hasSHA256 "98198123981273981273918273912738" ;
      eco:hasAccessDecoratorResource &lt;notebook-decorator-en-1.0&gt; .

  <#en-v11>
      a eco:AccessDecoratorVersion ;
      eco:isVersion "1.1.0" ;
      eco:hasSHA256 "12312312371273712731872371273712" ;
      eco:hasAccessDecoratorResource &lt;notebook-decorator-en-1.1&gt; .
  </pre>
</figure>

<figure id="fig-access-decorator-resource">
  <figcaption>An [=Access Decorator Resource=] referenced
  by the [Access Need Decorator Index](#fig-access-need-decorator-index)
  </figcaption>
  <pre highlight="turtle">
  @prefix skos: &lt;http://www.w3.org/2004/02/skos/core#&gt; .
  @prefix eco: &lt;http://www.w3.org/ns/solid/ecosystem#&gt; .
  @prefix note: &lt;http://shapetrees.pub/ns/note#&gt; .

  <> a eco:AccessDecoratorResource .

  <#notebook-collaboration-decorator>
    a eco:AccessNeedGroupDecorator ;
    eco:hasAccessNeedGroup &lt;#notebook-collaboration-group&gt; ;
    skos:prefLabel "Collaborate on notes"@en .
    skos:definition "Allowing for full reading and writing of notebooks and notes"@en .

  <#notebook-decorator>
    a eco:AccessNeedDecorator ;
    eco:hasAccessNeedGroup &lt;#notebook-collaboration-group&gt; ;
    eco:registeredShapeTree &lt;note:notebook-tree&gt; ;
    skos:prefLabel "Notebooks can be presented along with a list of their contents and read / written"@en .

  <#note-decorator>
    a eco:AccessNeedDecorator ;
    eco:hasAccessNeedGroup &lt;#notebook-collaboration-group&gt; ;
    eco:registeredShapeTree &lt;note:note-tree&gt; ;
    skos:prefLabel "Notes can be accessed and written"@en .
  </pre>
</figure>

### Access Need Group ### {#needs-access-need-group}

An <dfn>Access Need Group</dfn> is a collection of [=Access Needs=]
that a given [=Agent=] and/or [=Application=] uses to communicate a data
access request to other [=Agents=].

Each [=Access Need=] is associated with a specific [=shape tree=],
and [=shape trees=] provide both physical and/or virtual hierarchies.
The [[#prepare-group]] operation starts with each <dfn>Root Access Need</dfn>
linked via `hasAccessNeed`, and traverses the shape tree hierarchy,
creating a [=Prepared Access Need=] at each new [=shape tree=] and
linking them in a tree via `referencesPreparedAccessNeed` or `skos:narrower`.
Each <dfn>Access Need Override</dfn> that it encountered when traversing the
hierarchy applies new inherited defaults, or stops the recursion before
it continues through the remainder of the tree.

<table class="classinfo data" align="left" id="classAccessNeedGroup">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessNeedGroup](ecosystem.ttl#AccessNeedGroup)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>accessNecessity</td>
      <td>-</td>
      <td>`eco:AccessRequired`, `eco:AccessOptional`</td>
      <td>Necessity of the access to the requesting party</td>
    </tr>
    <tr>
      <td>hasAccessNeed</td>
      <td>-</td>
      <td>[AccessNeed](#classAccessNeed)</td>
      <td>Link to a [=Root Access Need=]</td>
    </tr>
    <tr>
      <td>hasAccessNeedOverride</td>
      <td>-</td>
      <td>[AccessNeed](#classAccessNeed)</td>
      <td>Link to an [=Access Need Override=]</td>
    </tr>
    <tr>
      <td>authenticatesAs</td>
      <td>[AccessNeedGroup](#classAccessNeedGroup)</td>
      <td>[=Agent=] or `eco:Pilot`</td>
      <td>[=Agent=] or mode the [=Application=] authenticates as</td>
    </tr>
    <tr>
      <td>hasAccessNeedDecoratorIndex</td>
      <td>[AccessNeedGroup](#classAccessNeedGroup)</td>
      <td>-</td>
      <td>Index of [=Acccess Decorator Resources=] to describe
      [=Access Need Group=] and [=Access Needs=]</td>
    </tr>
  </tbody>
</table>

The [AccessNeedGroupShape](#shexAccessNeedGroup) is used to validate an
instance of the [AccessNeedGroup](#classAccessNeedGroup) class.

<pre highlight="turtle" id="shexAccessNeedGroup">
<#AccessNeedGroupShape> {
  a [ eco:AccessNeedGroup ] ;
  eco:accessNecessity [ eco:AccessRequired eco:AccessOptional ] ;
  eco:authenticatesAs IRI ;
  eco:hasAccessNeed IRI+ ;
  eco:hasAccessNeedOverride IRI* ;
  eco:hasAccessDecoratorIndex IRI
}
</pre>

### Access Need ### {#needs-access-need}

An <dfn>Access Need</dfn> represents the requirement of one specific type
of data represented by a [=shape tree=], as part of an [=Access Need Group=].

Each [=Access Need=] represents a request to access, create, or manage
all or a subset of [=Registered Data Instances=] associated with a
[=Data Registration=] of a given [=shape tree=].

Specific [=Registered Data Instances=] may be requested by explicitly
associating them with the [=Access Need=] via
[hasRegisteredDataInstance](#classAccessNeed).

Each [=Access Need=] has one or more [=access modes=], and a property that
indicates the necessity of the [=Access Need=]; *required* or
*optional*. For example, an [=Access Need=] for read access to
[=shape tree=] `N` can be identified as a required item in the
[=Access Need Group=].

[=Access Needs=] are described using language-specific
[=Access Need Decorators=].

<table class="classinfo data" align="left" id="classAccessNeed">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessNeed](ecosystem.ttl#AccessNeed)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>inAccessNeedGroup</td>
      <td>[AccessNeed](#classAccessNeed)</td>
      <td>[AccessNeedGroup](#classAccessNeedGroup)</td>
      <td>[=Access Need Group=] that the [=Access Need=] is part of</td>
    </tr>
    <tr>
      <td>registeredShapeTree</td>
      <td>-</td>
      <td>`st:ShapeTree`</td>
      <td>The [=shape tree=] requested by the [=Access Need=]</td>
    </tr>
    <tr>
      <td>hasRegisteredDataInstance</td>
      <td>-</td>
      <td>-</td>
      <td>Request specific [=Registered Data Instances=] of the registered
      [=shape tree=]</td>
    </tr>
    <tr>
      <td>recursivelyAuthorize</td>
      <td>[AccessNeed](#classAccessNeed)</td>
      <td>`xsd:boolean`</td>
      <td>
        <ul>
          <li><b>true</b> - continue traversing shape tree hierarchy for
          authorization when true</li>
          <li><b>false</b> - stop traversal</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>accessMode</td>
      <td>-</td>
      <td>`acl:Read, acl:Write, acl:Control, acl:Append`</td>
      <td>Requested modes of access for the [=Access Need=]</td>
    </tr>
    <tr>
      <td>accessNecessity</td>
      <td>-</td>
      <td>`eco:AccessRequired`, `eco:AccessOptional`</td>
      <td>Necessity of the access to the requesting party</td>
    </tr>
  </tbody>
</table>

The [AccessNeedShape](#shexAccessNeed) is used to validate an
instance of the [AccessNeed](#classAccessNeed) class.

<pre highlight="turtle" id="shexAccessNeed">
<#AccessNeedShape> {
  a [ eco:AccessNeed ] ;
  eco:inAccessNeedGroup IRI+ ;
  eco:registeredShapeTree IRI ;
  eco:hasRegisteredDataInstance IRI* ;
  eco:recursivelyAuthorize [ true false ] ;
  eco:accessMode [ acl:Read acl:Write acl:Append acl:Control ]+ ;
  eco:accessNecessity [ eco:AccessRequired eco:AccessOptional ] ;
}
</pre>

### Prepared Access Need Group ### {#needs-prepared-access-need-group}

The [[#prepare-group]] operation takes an [=Access Need Group=] as input
and outputs a <dfn>Prepared Access Need Group</dfn>.

Preparing an [=Access Need Group=] includes:

* Getting an [=Access Need Group Decorator=] via [[#get-group-dec]]
* Recursing through the [=shape tree=] hierarchy of each [=Root Access Need=]
    in the [=Access Need Group=], and creating a [=Prepared Access Need=] for
    every [=shape tree=] encountered, applying [=Access Need Overrides=] when
    available.

A <dfn>Root Prepared Access Need</dfn> is the prepared version of the
corresponding [=Root Access Need=] in the source [=Access Need Group=].

<table class="classinfo data" align="left" id="classPreparedAccessNeedGroup">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [PreparedAccessNeedGroup](ecosystem.ttl#PreparedAccessNeedGroup)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>fromAccessNeedGroup</td>
      <td>[PreparedAccessNeedGroup](#classPreparedAccessNeedGroup)</td>
      <td>[AccessNeedGroup](#classAccessNeedGroup)</td>
      <td>The [=Access Need Group=] used to generate the
      [=Prepared Access Need Group=]</td>
    </tr>
    <tr>
      <td>hasAccessNeedGroupDecorator</td>
      <td>[PreparedAccessNeedGroup](#classPreparedAccessNeedGroup)</td>
      <td>[AccessNeedGroupDecorator](#classAccessNeedGroupDecorator)</td>
      <td>An [=Access Need Group Decorator=] that describes this
      [=Prepared Access Need Group=]</td>
    </tr>
    <tr>
      <td>authenticatesAs</td>
      <td>-</td>
      <td>[=Agent=] or `eco:Pilot`</td>
      <td>[=Agent=] or mode the [=Application=] authenticates as</td>
    </tr>
    <tr>
      <td>accessNecessity</td>
      <td>-</td>
      <td>`eco:AccessRequired`, `eco:AccessOptional`</td>
      <td>Necessity of the access to the requesting party</td>
    </tr>
    <tr>
      <td>hasPreparedAccessNeed</td>
      <td>[PreparedAccessNeedGroup](#classPreparedAccessNeedGroup)</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>Link to a [=Root Prepared Access Need=]</td>
    </tr>
  </tbody>
</table>

The [PreparedAccessNeedGroupShape](#shexPreparedAccessNeedGroup) is used to
validate an instance of the
[PreparedAccessNeedGroup](#classPreparedAccessNeedGroup) class.

<pre highlight="turtle" id="shexPreparedAccessNeedGroup">
<#PreparedAccessNeedGroupShape> {
  a [ eco:PreparedAccessNeedGroup ] ;
  eco:fromAccessNeedGroup IRI ;
  eco:hasAccessNeedGroupDecorator IRI ;
  eco:authenticatesAs IRI ;
  eco:accessNecessity [ eco:AccessRequired eco:AccessOptional ] ;
  eco:hasPreparedAccessNeed IRI+ ;
}
</pre>

### Prepared Access Need ### {#needs-prepared-access-need}

A <dfn>Prepared Access Need</dfn> is generated by the [[#prepare-group]]
operation as it processes an input [=Access Need Group=]. A
[=Prepared Access Need=] is added to the [=Prepared Access Need Group=]
for every unique [=shape tree=] encountered as the operation traverses the
[=shape tree=] hierarchy.

<table class="classinfo data" align="left" id="classPreparedAccessNeed">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [PreparedAccessNeed](ecosystem.ttl#PreparedAccessNeed)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>inPreparedAccessNeedGroup</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>[PreparedAccessNeedGroup](#classPreparedAccessNeedGroup)</td>
      <td>[=Prepared Access Need Group=] the [=Prepared Access Need=] belongs to</td>
    </tr>
    <tr>
      <td>hasShapeTreeDecorator</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>`st:ShapeTreeDecorator`</td>
      <td>Decorator associated with the [=shape tree=] that describes the
      name of the shape-tree and what data it represents in the preferred
      language of the [=Agent=]</td>
    </tr>
    <tr>
      <td>hasAccessNeedDecorator</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>[AccessNeedDecorator](#classAccessNeedDecorator)</td>
      <td>Decorator that explains the reason for the access need in the
      preferred language of the [=Agent=]</td>
    </tr>
    <tr>
      <td>hasDataGrant</td>
      <td>-</td>
      <td>[DataGrant](#classDataGrant)</td>
      <td>[=Data Grant=] associated with the [=Prepared Access Need=],
      established when the [=Access Grant=] is created</td>
    </tr>
    <tr>
      <td>hasRegisteredDataInstance</td>
      <td>-</td>
      <td>[RegisteredDataInstance](#)</td>
      <td>Links to any specific [=Registered Data Instances=] that were
      included in the original request</td>
    </tr>
    <tr>
      <td>registeredShapeTree</td>
      <td>-</td>
      <td>`st:ShapeTree`</td>
      <td>[=Shape tree=] associated with the [=Prepared Access Need=]</td>
    </tr>
    <tr>
      <td>accessMode</td>
      <td>-</td>
      <td>`acl:Read, acl:Write, acl:Control, acl:Append`</td>
      <td>Requested modes of access for the [=Prepared Access Need=]</td>
    </tr>
    <tr>
      <td>accessNecessity</td>
      <td>-</td>
      <td>`eco:AccessRequired`, `eco:AccessOptional`</td>
      <td>Necessity of the access to the requesting party</td>
    </tr>
    <tr>
      <td>supportedByPreparedAccessNeed</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>A [=Prepared Access Need=] whose [=shape tree=] `st:supports` the
      [=shape tree=] of this [=Prepared Access Need=]</td>
    </tr>
    <tr>
      <td>supportsPreparedAccessNeed</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>A [=Prepared Access Need=] that [=shape tree=] of this
      [=Prepared Access Need=] `st:supports`</td>
    </tr>
    <tr>
      <td>referencesPreparedAccessNeed</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>The next [=Prepared Access Need=] in a virtual hierarchy</td>
    </tr>
    <tr>
      <td>skos:narrower</td>
      <td>-</td>
      <td>[PreparedAccessNeed](#classPreparedAccessNeed)</td>
      <td>The next [=Prepared Access Need=] in a virtual hierarchy where
      the regular [=shape tree=] hierarchy has been extended to include
      a skos hierarchy.</td>
    </tr>
  </tbody>
</table>

The [PreparedAccessNeedShape](#shexPreparedAccessNeed) is used to
validate an instance of the
[PreparedAccessNeed](#classPreparedAccessNeed) class.

<pre highlight="turtle" id="shexPreparedAccessNeed">
<#PreparedAccessNeedShape> {
  a [ eco:PreparedAccessNeed ] ;
  eco:inPreparedAccessNeedGroup IRI+ ;
  eco:hasShapeTreeDecorator IRI ;
  eco:hasAccessNeedDecorator IRI? ;
  eco:hasDataGrant IRI? ;
  eco:hasRegisteredDataInstance IRI* ;
  eco:registeredShapeTree IRI ;
  eco:accessMode [ acl:Read acl:Write acl:Append acl:Control ]+ ;
  eco:accessNecessity [ eco:AccessRequired eco:AccessOptional ] ;
  eco:supportedBy IRI* ;
  eco:supports IRI
  eco:referencesPreparedAccessNeed IRI* ;
  skos:narrower IRI* ;
}
</pre>

### Access Decorator Index ### {#needs-access-decorator-index}

An <dfn>Access Decorator Index</dfn> is a listing of one or more
[=Access Decorator Series=].

<table class="classinfo data" align="left" id="classAccessDecoratorIndex">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessDecoratorIndex](ecosystem.ttl#AccessDecoratorIndex)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>defaultLanguage</td>
      <td>[AccessDecoratorIndex](#classAccessDecoratorIndex)</td>
      <td>`xsd:language`</td>
      <td>Default language to select if not provided as input</td>
    </tr>
    <tr>
      <td>hasSeries</td>
      <td>[AccessDecoratorIndex](#classAccessDecoratorIndex)</td>
      <td>[AccessDecoratorSeries](#classAccessDecoratorSeries)</td>
      <td>Link to an [=Access Decorator Series=]</td>
    </tr>
  </tbody>
</table>

The [AccessDecoratorIndexShape](#shexAccessDecoratorIndex) is used to
validate an instance of the [AccessDecoratorIndex](#classAccessDecoratorIndex)
class.

<pre highlight="turtle" id="shexAccessDecoratorIndex">
<#AccessDecoratorIndexShape> {
  a [ eco:AccessDecoratorIndex ] ;
  eco:defaultLanguage xsd:language ;
  eco:hasSeries @AccessDecoratorSeries+ ;
}
</pre>

#### Access Decorator Series #### {#needs-access-decorator-series}

An <dfn>Access Decorator Series</dfn> has one or
more [=Access Decorator Versions=] in a given language.

<table class="classinfo data" align="left" id="classAccessDecoratorSeries">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessDecoratorSeries](ecosystem.ttl#AccessDecoratorSeries)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>usesLanguage</td>
      <td>[AccessDecoratorSeries](#classAccessDecoratorSeries)</td>
      <td>xsd:language</td>
      <td>Language code associated with the [=Access Decorator Series=]</td>
    </tr>
    <tr>
      <td>hasVersion</td>
      <td>[AccessDecoratorSeries](#classAccessDecoratorSeries)</td>
      <td>[AccessDecoratorVersion](#classAccessDecoratorVersion)</td>
      <td>Links to an [=Access Decorator Version=] in the series</td>
    </tr>
  </tbody>
</table>

The [AccessDecoratorSeriesShape](#shexAccessDecoratorSeries) is used to
validate an instance of the [AccessDecoratorSeries](#classAccessDecoratorSeries)
class.

<pre highlight="turtle" id="shexAccessDecoratorSeries">
<#AccessDecoratorSeriesShape> {
  a [ eco:AccessDecoratorSeries ] ;
  eco:usesLanguage xsd:language ;
  eco:hasVersion @AccessDecoratorVersion+ ;
}
</pre>

#### Access Decorator Version #### {#needs-access-decorator-version}

An <dfn>Access Decorator Version</dfn> is a versioned instance of
a given [=Access Decorator Resource=].

<table class="classinfo data" align="left" id="classAccessDecoratorVersion">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [PreparedAccessNeedGroup](ecosystem.ttl#PreparedAccessNeedGroup)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>isVersion</td>
      <td>[AccessDecoratorVersion](#classAccessDecoratorVersion)</td>
      <td>xsd:string</td>
      <td>Semantic version of the [=Access Decorator Resource=] (e.g. "1.1.0")</td>
    </tr>
    <tr>
      <td>hasSHA256</td>
      <td>[AccessDecoratorVersion](#classAccessDecoratorVersion)</td>
      <td>xsd:string</td>
      <td>SHA-256 hash of the linked [=Access Decorator Resource=]</td>
    </tr>
    <tr>
      <td>hasAccessDecoratorResource</td>
      <td>[AccessDecoratorVersion](#classAccessDecoratorVersion)</td>
      <td>[AccessDecoratorResource](#classAccessDecoratorResource)</td>
      <td>Links to the actual [=Access Decorator Resource=] document</td>
    </tr>
  </tbody>
</table>

The [AccessDecoratorVersionShape](#shexAccessDecoratorVersion) is used to
validate an instance of the
[AccessDecoratorVersion](#classAccessDecoratorVersion) class.

<pre highlight="turtle" id="shexAccessDecoratorVersion">
<#AccessDecoratorVersionShape> {
  a [ eco:AccessDecoratorVersion ] ;
  eco:isVersion xsd:string ;
  eco:hasSHA256 xsd:string ;
  eco:hasAccessDecoratorResource IRI ;
}
</pre>

### Access Decorator Resource ### {#needs-access-decorator-resource}

An <dfn>Access Decorator Resource</dfn> is a document that contains
[=Access Need Group Decorators=] and [=Access Need Decorators=] in a
given language.

<table class="classinfo data" align="left" id="classAccessDecoratorResource">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessDecoratorResource](ecosystem.ttl#AccessDecoratorResource)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><i>No properties</i></td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
  </tbody>
</table>

#### Access Need Group Decorator #### {#needs-access-need-group-decorator}

An <dfn>Access Need Group Decorator</dfn> provides a subject name and
more in depth description that explains why a given [=Access Need Group=]
is being requested of an [=Agent=].

<table class="classinfo data" align="left" id="classAccessNeedGroupDecorator">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessNeedGroupDecorator](ecosystem.ttl#AccessNeedGroupDecorator)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasAccessNeedGroup</td>
      <td>-</td>
      <td>[AccessNeedGroup](#classAccessNeedGroup)</td>
      <td>[=Access Need Group=] the decorator applies to</td>
    </tr>
    <tr>
      <td>skos:preflabel</td>
      <td>-</td>
      <td>`xsd:string`</td>
      <td>Short label (title) for the [=Access Need Group=]</td>
    </tr>
    <tr>
      <td>skos:definition</td>
      <td>-</td>
      <td>`xsd:string`</td>
      <td>Description of why the [=Access Need Group=] requires the
      access it is requesting.</td>
    </tr>
  </tbody>
</table>

The [AccessNeedGroupDecoratorShape](#shexAccessNeedGroupDecorator) is used to
validate an instance of the
[AccessNeedGroupDecorator](#classAccessNeedGroupDecorator) class.

<pre highlight="turtle" id="shexAccessNeedGroupDecorator">
<#AccessNeedGroupDecoratorShape> {
  a [ eco:AccessNeedGroupDecorator ] ;
  eco:hasAccessNeedGroup IRI ;
  skos:prefLabel xsd:string ;
  skos:definition xsd:string
}
</pre>

#### Access Need Decorator #### {#needs-access-need-decorator}

An <dfn>Access Need Decorator</dfn> provides a specific
explanation of why that data type is being requested.

<table class="classinfo data" align="left" id="classAccessNeedDecorator">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessNeedDecorator](ecosystem.ttl#AccessNeedDecorator)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasAccessNeedGroup</td>
      <td>-</td>
      <td>[AccessNeedGroup](#classAccessNeedGroup)</td>
      <td>[=Access Need Group=] the decorator applies to</td>
    </tr>
    <tr>
      <td>registeredShapeTree</td>
      <td>-</td>
      <td>`st:ShapeTree`</td>
      <td>[=Shape tree=] associated with the [=Access Need=] the decorator
      should apply to</td>
    </tr>
    <tr>
      <td>skos:prefLabel</td>
      <td>-</td>
      <td>`xsd:string`</td>
      <td>Specific explanation of why that data type is being requested</td>
    </tr>
  </tbody>
</table>

The [AccessNeedDecoratorShape](#shexAccessNeedDecorator) is used to
validate an instance of the
[AccessNeedDecorator](#classAccessNeedDecorator) class.

<pre highlight="turtle" id="shexAccessNeedDecorator">
<#AccessNeedDecoratorShape> {
  a [ eco:AccessNeedDecorator ] ;
  eco:hasAccessNeedGroup IRI ;
  eco:registeredShapeTree IRI ;
  skos:prefLabel xsd:string
}
</pre>

## Operations ## {#needs-operations}

The following operations explain how to process [=Access Need Groups=]
so they can be presented to an [=Agent=] in
[[#access-operations|Access Grant Operations]]

* [[#prepare-group]]
* [[#prepare-need]]
* [[#get-group-dec]]
* [[#get-need-dec]]

### Prepare Access Need Group ### {#prepare-group}

This operation takes a given [=Access Need Group=] with a number of associated
[=Access Needs=] and processes them to produce a [=Prepared Access Need Group=]
with [=Prepared Access Needs=] that are ready to present to a given [=Agent=]
in [[#access-operations|Access Grant Operations]].

1. The [=shape tree=] associated with each [=Root Access Need=] is
    traversed to the desired level of recursion, including across references.
    A [=Prepared Access Need=] is added in a linked hierarchy
    starting with the [=Root Access Need=], representing every unique
    [=shape tree=] that was traversed.
2. Decorators are looked up and linked to the
    [=Prepared Access Need Group=] and where available for every
    [=Prepared Access Need=]
3. Any [=Supporting Access Needs=] are associated with [=Prepared Access Needs=].

#### Inputs #### {#prepare-group-inputs}

* Let `GROUP` be an [=Access Need Group=]
* Let `LANG` be the [=Agent's=] preferred language

#### Outputs #### {#prepare-group-outputs}

* A [=Prepared Access Need Group=] generated from the input `GROUP`, with
    an associated set of [=Prepared Access Needs=].

#### Operation Details #### {#prepare-group-details}

1. Perform a validation of the RDF graph of `GROUP` against
    [eco:AccessNeedGroupShape](ecosystem.shex#AccessNeedGroupShape).
    <em class="rfc2119">MUST</em> return a status code of 400 if
    validation fails.
1. Let `ALLNEEDS` be the combined set of [=Access Needs=] linked via
    `GROUP hasAccessNeed` and `GROUP hasAccessNeedOverride`
1. Let `OVERRIDES` be the [=Access Needs=] linked via `GROUP hasAccessNeedOverride`
1. Let `TREEDECS` represent all [=Shape Tree Decorators=] associated with `ALLNEEDS`
1. Let `ALLDECS` represent all [=Access Need Decorators=] associated with `ALLNEEDS`
1. Let `PGROUP` be a [=Prepared Access Need Group=]
1. Let `PGROUP hasAccessNeedDecorator` be the [=Access Need Group Decorator=]
    returned from [[#get-group-dec]] with inputs: `GROUP`, `LANG`
1. Let `PGROUP fromAccessNeedGroup` be `GROUP`
1. Let `PGROUP accessNecessity` be `GROUP accessNecessity`
1. Let `PGROUP authenticatesAs` be `GROUP authenticatesAs`
1. For each [=Root Access Need=] `ROOT` linked via `GROUP hasAccessNeed`
    1. Let `PGROUP hasPreparedAccessNeed` be linked to the
        [=Prepared Root Access Need=] returned by
        [[#prepare-need]] with inputs: `ROOT registeredShapeTree`, `ROOT`,
        `ALLNEEDS`, `OVERRIDES`, `TREEDECS`, `ALLDECS`, `LANG`
1. Let `ALLPREPARED` represent all [=Prepared Access Needs=] linked via
    `PGROUP hasPreparedAccessNeed`, as well as all [=Prepared Access Needs=]
    linked to them via `referencesPreparedAccessNeed` or `skos:narrower`.
1. For each [=Root Prepared Access Need=] `PROOT` linked via `PGROUP hasPreparedAccessNeed`
    1. Call [[#link-supported]] with inputs: `PROOT`, `ALLPREPARED`

### Prepare Access Need ### {#prepare-need}

This operation is called recursively to build up a linked hierarchy of
[=Prepared Access Needs=] in concert with the [[#prepare-need-walk]] operation.

#### Inputs #### {#prepare-need-inputs}

* Let `TREE` be the current [=shape tree=] in context
* Let `LASTNEED` be the [=Access Need=] in context
* Let `ALLNEEDS` be the combined set of [=Access Needs=] linked via
    `GROUP hasAccessNeed` and `GROUP hasAccessNeedOverride`
* Let `OVERRIDES` be the [=Access Needs=] linked via `GROUP hasAccessNeedOverride`
* Let `TREEDECS` represent all [=Shape Tree Decorators=] associated with `ALLNEEDS`
* Let `ALLDECS` represent all [=Access Need Decorators=] associated with `ALLNEEDS`
* Let `LANG` be the [=Agent's=] preferred language

#### Outputs #### {#prepare-need-outputs}

* A [=Prepared Access Need=] with a linked hierarchy of
    [=Prepared Access Needs=] associated with it

#### Operation Details #### {#prepare-need-details}

1. Let `TOPTREEDEC` be the [=Shape Tree Decorator=]
    returned from the [Get Shape Tree Decorator](#) operation with
    inputs: `TREE`, `LANG`
1. Let `SPECIFICNEED` be the [=Access Need=] returned from the
    [[#prepare-need-getspecific]] operation with inputs:
    `TREE`, `OVERRIDES`, `LASTNEED`
1. return the [=Prepared Access Need=] returned by calling
    [[#prepare-need-walk]] with inputs:
    `TREE`, `TOPTREEDEC`, `SPECIFICNEED`, `ALLDECS`, `ALLNEEDS`,
    `OVERRIDES`, `TREEDECS`, `LANG`

#### _walkDecorators #### {#prepare-need-walk}

This operation is called recursively to build up a linked hierarchy of
[=Prepared Access Needs=] in concert with the [[#prepare-need]] operation.

##### Inputs ##### {#walk-inputs}

* Let `TREE` be the current [=shape tree=] in context
* Let `TREEDEC` be the current [=Shape Tree Decorator=] in context
* Let `NEED` be the [=Access Need=] in context
* Let `ALLDECS` represent all [=Access Need Decorators=] associated with `ALLNEEDS`
* Let `ALLNEEDS` be the combined set of [=Access Needs=] linked via
    `GROUP hasAccessNeed` and `GROUP hasAccessNeedOverride`
* Let `OVERRIDES` be the [=Access Needs=] linked via `GROUP hasAccessNeedOverride`
* Let `TREEDECS` represent all [=Shape Tree Decorators=] associated with `ALLNEEDS`
* Let `LANG` be the [=Agent's=] preferred language

##### Outputs ##### {#walk-outputs}

* A [=Prepared Access Need=] with a linked hierarchy of
    [=Prepared Access Needs=] associated with it

##### Operation Details ##### {#walk-details}

1. Let `PREPARED` be a new [=Prepared Access Need=]
1. Let `PREPARED registeredShapeTree` be `TREE`
1. Let `PREPARED accessNecessity` be set to `NEED`'s `accessNecessity`
1. Let `PREPARED accessMode` be all of `NEED`'s `accessMode`s
1. Let `PREPARED hasAccessNeedDecorator` be the [=Access Need Decorator=]
    returned from [[#get-need-dec]] with inputs: `NEED`, `LANG`
1. Let `PREPARED hasShapeTreeDecorator` be `TREEDEC`
1. If `TREEDEC skos:narrower`
    1. Let `NARROWERDEC` be `TREEDEC skos:narrower`
    1. Let `NARROWERTREE` be `NARROWERDEC hasShapeTree`
    1. Let `NARROWERNEED` be the [=Access Need=] returned from the
        [[#prepare-need-getspecific]] operation with inputs:
        `NARROWERTREE`, `OVERRIDES`, `NEED`
    1. Let `PREPARED skos:narrower` be the [=Prepared Access Need=] returned
        from calling [[#prepare-need-walk]] with inputs:
        `NARROWERTREE`, `NARROWERDEC`, `NARROWERNEED`, `ALLDECS`, `ALLNEEDS`,
        `OVERRIDES`, `TREEDECS`, `LANG`
1. For each [=shape tree=] `REFTREE` linked via `TREE st:references`
    1. Call [[#prepare-need]] with inputs `REFTREE`, `NEED`,
        `ALLNEEDS`, `OVERRIDES`, `TREEDECS`, `ALLDECS`, `LANG`

#### _getSpecificAccessNeed #### {#prepare-need-getspecific}

This operation looks through all of the [=Access Need Overrides=] associated
with a given [=Access Need Group=] to see if there is an
[=Access Need Override=] for the input [=shape tree=]. If there is not,
it will effective inherit its defaults from the last [=Access Need=] instead.

##### Inputs ##### {#getspecific-inputs}

* Let `TREE` be the current [=shape tree=] in context
* Let `DEFAULTNEED` be the default [=Access Need=] to return
* Let `OVERRIDES` be the [=Access Needs=] linked via `GROUP hasAccessNeedOverride`

##### Outputs ##### {#getspecific-outputs}

* An [=Access Need=]

##### Operation Details ##### {#getspecific-details}

1. For each [=Access Need=] `NEED` in `OVERRIDES`
    1.  return `NEED` if `NEED registeredShapeTree` is `TREE`
1. return `DEFAULTNEED`

### Link Supported Prepared Access Needs ### {#link-supported}

This is a recursive operation that iterates through all of the
[=Prepared Access Needs=] associated with a [=Prepared Access Need Group=]
and links together any that have a support relationship.

A support relationship exists when the [=shape tree=] associated with one
[=Prepared Access Need=] has an `st:supports` predicate that links
to the [=shape tree=] of another [=Prepared Access Need=]. They are
linked bi-directionally through the `supportsPreparedAccessNeed` and
`supportedByPreparedAccessNeed` properties.

#### Inputs #### {#link-supported-inputs}

* Let `PNEED` be a [=Prepared Access Need=]
* Let `ALLPREPARED` be all [=Prepared Access Needs=] associated with a
    given [=Prepared Access Need Group=]

#### Outputs #### {#link-supported-outputs}

* None

#### Operation Details #### {#link-supported-details}

1. Let `TREE` be `PNEED registeredShapeTree`
1. If `TREE st:supports`
    1. Let `SUPPORTEDTREE` be the [=shape tree=] linked by `TREE st:supports`
    1. For each [=Prepared Access Need=] `PREPARED` in `ALLPREPARED`
        1. Let `SUPPORTEDNEED` be the return of [[#iterate-supported]] with
            inputs: `ALLPREPARED`, `TREE`
        1. Let `PNEED supportsPreparedAccessNeed` be `SUPPORTEDNEED`
        1. Let `SUPPORTEDNEED supportedByPreparedAccessNeed` be `PNEED`
1. For each [=Prepared Access Need=] `REFNEED` linked by
    `PNEED referencesPreparedAccessNeed`
    1. Call [[#link-supported]] with inputs: `REFNEED`, `ALLPREPARED`
1. For each [=Prepared Access Need=] `NARROWERNEED` linked by
    `PNEED skos:narrower`
    1. Call [[#link-supported]] with inputs: `NARROWERNEED`, `ALLPREPARED`

#### Iterate for Supported Prepared Access Needs #### {#iterate-supported}

This is a recursive function that iterates through a linked hierarchy of
[=Prepared Access Needs=] looking for a [=Prepared Access Need=] with a
matching [=shape tree=].

##### Inputs ##### {#iterate-inputs}

* Let `PNEED` be a [=Prepared Acecss Need=]
* Let `TREE` be a [=shape tree]

##### Outputs ##### {#iterate-outputs}

* Returns a [=Prepared Access Need=]

##### Operation Details ##### {#iterate-details}

1. Return `PNEED` if `PNEED registeredShapeTree` is `TREE`
1. For each [=Prepared Access Need=] `REFNEED` linked by
    `PNEED referencesPreparedAccessNeed`
    1. Call [[#iterate-supported]] with inputs: `REFNEED`, `TREE`
1. For each [=Prepared Access Need=] `NARROWERNEED` linked by
    `PNEED skos:narrower`
    1. Call [[#iterate-supported]] with inputs: `NARROWERNEED`, `TREE`
1. Return `NULL`

### Get Access Decorator Resource ### {#get-access-dec}

This operation returns the appropriate [=Access Decorator Resource=]
from an input [=Access Decorator Index=] for the provided language.
If the provided language is not available, a default language is used instead.

#### Inputs #### {#get-access-dec-inputs}

* Let `INDEX` be an [=Access Decorator Index=]
* Let `LANG` be the [=Agent's=] preferred language

#### Outputs #### {#get-access-dec-outputs}

* Let `DECR` be an [=Access Decorator Resource=] from `INDEX`

#### Operation Details #### {#get-access-dec-details}

1. Let `USESERIES` be `INDEX defaultSeries`
1. Let `USEVERSION` be an unassigned [=Access Decorator Version=]
1. For each [=Access Decorator Series=] `SERIES` in `INDEX`
    1. Let `USESERIES` be `SERIES` if `SERIES usesLanguage` == `LANG`
1. <em class="rfc2119">MUST</em> return a status code
    of 404 if no [=Access Decorator Series=] are found.
1. For each [=Access Decorator Version=] `VERSION` in `USESERIES hasVersion`
    1. Let `USEVERSION` be `VERSION` if `VERSION` is a more recent
        [semantic version](https://semver.org/) than `USEVERSION` or if
        `USEVERSION` is unassigned.
1. <em class="rfc2119">MUST</em> return a status code
    of 404 if no [=Access Decorator Versions=] are found.
1. Let `DECR` be the [=Access Decorator Resource=] linked
    from `USEVERSION hasAccessDecoratorResource`
1. <em class="rfc2119">MUST</em> return a status code
    of 404 if `DECR` is unassigned.
1. return `DECR`

### Get Access Need Group Decorator ### {#get-group-dec}

This operation returns the appropriate [=Access Need Group Decorator=]
for an input [=Access Need Group=] in the provided language. If the
provided language is not available, a default language is used instead.

#### Inputs #### {#get-group-dec-inputs}

* Let `GROUP` be an [=Access Need Group=]
* Let `LANG` be the [=Agent's=] preferred language

#### Outputs #### {#get-group-dec-outputs}

* Let `GDEC` be an [=Access Need Group Decorator=] associated with `GROUP`

#### Operation Details #### {#get-group-dec-details}

1. Let `DECR` be the [=Access Decorator Resource=] returned by [[#get-group-dec]]
    with inputs: `GROUP hasAccessDecoratorIndex`, `LANG`
1. Let `USEGDEC` be an unassigned [=Access Need Group Decorator=]
1. Let `GDECS` be all [=Acess Need Group Decorators=] in `DECR`
1. For each [=Acces Need Group Decorator] `GDEC` in `GDECS`
  1. Let `USEGDEC` be `GDEC` if `GDEC hasAccessNeedGroup` is `GROUP`
1. <em class="rfc2119">MUST</em> return a status code
    of 404 if `USEGDEC` is unassigned
1. return `USEGDEC`

### Get Access Need Decorator ### {#get-need-dec}

This operation returns the appropriate [=Access Need Decorator=]
for an input [=Access Need=] in the provided language. If the
provided language is not available, a default language is used instead.

#### Inputs #### {#get-need-dec-inputs}

* Let `NEED` be an [=Access Need=]
* Let `LANG` be the [=Agent's=] preferred language

#### Outputs #### {#get-need-dec-outputs}

* Let `NDEC` be an [=Access Need Decorator=] associated with `NEED`

#### Operation Details #### {#get-need-dec-details}

1. Let `GROUP` be `NEED inAccessNeedGroup`
1. Let `DECR` be the [=Access Decorator Resource=] returned by [[#get-group-dec]]
    with inputs: `GROUP hasAccessDecoratorIndex`, `LANG`
1. Let `USENDEC` be an unassigned [=Access Need Decorator=]
1. Let `NDECS` be all [=Acess Need Decorators=] in `DECR`
1. For each [=Acces Need Decorator] `NDEC` in `NDECS`
  1. Let `USENDEC` be `NDEC` if `NDEC hasAccessNeedGroup` is `GROUP` and
      `NDEC registeredShapeTree` is `NEED registeredShapeTree`
1. <em class="rfc2119">MUST</em> return a status code
    of 404 if `USENDEC` is unassigned
1. return `USENDEC`


Access Grants {#access}
=====================

## Overview ## {#access-overview}

## Data Model ## {#access-datamodel}

### Summary ### {#access-datamodel-summary}

<figure id="fig-access-model">
  <img src="access-model.svg" width=100%/>
  <figcaption>Data model for the access registry</figcaption>
</figure>

The [=Access Registry=] extends the [[#reg-model]] with type-specific
subclasses and subproperties.

An [=Agent=] has a [=Registrar=] that links to [=Access Registry Sets=]
via the [eco:hasAccessRegistrySet](ecosystem.ttl#hasAccessRegistrySet) property.

A [=Access Registry Set=] links to any number of [=Access Registries=] via
the [eco:hasRegistry](ecosystem.ttl#hasRegistry) property.

An [=Access Registry=] links to any number of registered [=Access Grants=]
via the [eco:hasRegistration](ecosystem.ttl#hasRegistration) property.

<figure id="fig-access-registrar">
  <figcaption>A [=Registrar=] at https://alice.pod.example/registries/#registrar
  linking to an [=Access Registry Set=]</figcaption>
  <pre highlight="turtle">
  <#registrar>
    a eco:Registrar;
    eco:hasAccessRegistrySet &lt;https://alice.pod.example/registries/access#set&gt; .
  </pre>
  </figure>
</figure>

<figure id ="fig-access-registry-set">
   <figcaption>An [=Access Registry Set=] at
   https://alice.pod.example/registries/access#set linking to two different
  [=Access Registries=]</figcaption>
  <pre highlight="turtle">
  <#set>
    a eco:AccessRegistrySet;
    eco:hasRegistry &lt;https://alice.pod.example/access/#registry&gt; ,
                    &lt;https://alice.otherpod.example/access/#registry&gt; .
  </pre>
</figure>

<figure id="fig-access-registry">
  <figcaption>An [=Access Registry=] at https://alice.pod.example/access/#registry
  linking to several registered [=Access Grants=]</figcaption>
  <pre highlight="turtle">
  <#registry>
    a eco:AccessRegistry ;
    eco:hasRegistration &lt;ab3d0023-3860-4358-ae33-8d3af1097b9d/#grant&gt ,
                        &lt;ad7b935f-ced9-4ce6-835f-5c6abc046228/#grant&gt ,
                        &lt;5ed73c65-ce77-4c8a-8f7e-9715b90307e6/#grant&gt .
  </pre>
</figure>

<figure id="fig-access-grant">
  <figcaption>An [=Access Grant=] at
  https://alice.pod.example/access/ab3d0023-3860-4358-ae33-8d3af1097b9d/#grant
  </figcaption>
  <pre highlight="turtle">
  <#grant>
    a eco:AccessGrant ;
    eco:hasAccessGrantSubject <#grant-subject> ;
    eco:hasPreparedAccessNeedGroup <#pag-notebook-group> ;
    eco:hasDataGrant <#notebook-grant>, <#note-grant> .

  <#grant-subject>
    a eco:AccessGrantSubject ;
    eco:accessByAgent https://alice.pod.example/profile/id#me ;
    eco:accessByApplication https://nevernote.example/id#agent .

  <#notebook-grant>
    a eco:DataGrant ;
    eco:hasRegistration data:notebook-tree ;
    eco:registeredShapeTree note:notebook-tree ;
    eco:satisfiesPreparedAccessNeed <#pan-notebook> ;
    eco:accessMode acl:Read, acl:Write ;
    eco:scopeOfDataGrant eco:AllInstances ;

  <#note-grant>
    a eco:DataGrant ;
    eco:hasRegistration data:note-tree ;
    eco:registeredShapeTree note:note-tree ;
    eco:satisfiesPreparedAccessNeed <#pan-note> ;
    eco:accessMode acl:Read, acl:Write ;
    eco:scopeOfDataGrant eco:AllInstances ;

  <#pag-notebook-group>
    a eco:PreparedAccessNeedGroup ;
    eco:fromAccessNeedGroup ex:accessNotebookGroup ;
    eco:hasAccessNeedGroupDecorator ex:accessNotebookGroupDecorator ;
    eco:accessNecessity eco:AccessRequired ;
    eco:authenticatesAs eco:Pilot ;
    eco:hasPreparedAccessNeed <#pan-notebook> .

  <#pan-notebook>
      a eco:PreparedAccessNeed ;
      eco:registeredShapeTree note:notebook-tree ;
      eco:accessMode acl:Read, acl:Write ;
      eco:accessNecessity eco:AccessRequired ;
      eco:hasAccessNeedDecorator ex:notebookAccessDecorator ;
      eco:hasShapeTreeDecorator note:notebookDecorator ;
      eco:referencesPreparedAccessNeed <#pan-notes> ;
      eco:hasDataGrant <#notebook-grant> .

  <#pan-note>
      a eco:PreparedAccessNeed ;
      eco:registeredShapeTree note:note-tree ;
      eco:accessMode acl:Read, acl:Write ;
      eco:accessNecessity eco:AccessRequired ;
      eco:hasAccessNeedDecorator ex:noteAccessDecorator ;
      eco:hasShapeTreeDecorator note:noteDecorator ;
      eco:hasDataGrant <#note-grant> .
  </pre>
</figure>

### Access Registry Set ### {#datamodel-registry-set}

An <dfn>Access Registry Set</dfn> is a [=Registry Set=] specifically
made up of [=Access Registries=].

<table class="classinfo data" align="left" id="classAccessRegistrySet">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4 text-align=left>
        [AccessRegistrySet](ecosystem.ttl#AccessRegistrySet)
        a rdfs:subClassOf [[#reg-model|RegistrySet]]
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasRegistry</td>
      <td>RegistrySet</td>
      <td>Registry</td>
      <td>Link to associated [=Access Registries=]</td>
    </tr>
  </tbody>
</table>

The [AccessRegistrySetShape](#shexAccessRegistrySet) is used to validate
an instance of the [AccessRegistrySet](#classAccessRegistrySet) class.

<pre highlight="turtle" id="shexAccessRegistrySet">
<#AccessRegistrySetShape> {
  a [ eco:AccessRegistrySet ] ;
  eco:hasRegistry IRI+
}
</pre>

The [AccessRegistrySetTree](ecosystem.tree#access-registry-set-tree)
is assigned to a resource to ensure it will validate against the
[AccessRegistrySetShape](#shexAccessRegistrySet).

<pre highlight="turtle" id="treeAccessRegistrySet">
<#access-registry-set-tree>
  a st:ShapeTree;
  st:expectsType st:ShapeTreeResource ;
  st:validatedBy &lt;ecos#AccessRegistrySetShape&gt; ;
  st:matchesUriTemplate "access" .
</pre>

### Access Registry ### {#datamodel-access-registry}

An <dfn>Access Registry</dfn> is a collection of
[=Access Grants=] stored in a specific location in a [=pod=].

<table class="classinfo data" align="left" id="classAccessRegistry">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessRegistry](ecosystem.ttl#AccessRegistry)
        a rdfs:subClassOf [[#reg-model|Registry]]
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasRegistration</td>
      <td>Registry</td>
      <td>Registration</td>
      <td>Link to associated [=Access Grants=]</td>
    </tr>
  </tbody>
</table>

The [AccessRegistryShape](#shexAccessRegistry) is used to validate an
instance of the [AccessRegistry](#classAccessRegistry) class.

<pre highlight="turtle" id="shexAccessRegistry">
<#AccessRegistryShape> {
  a [ eco:AccessRegistry ] ;
  eco:hasRegistration IRI*
}
</pre>

The [AccessRegistryTree](ecosystem.tree#access-registry-tree) is assigned
to a container resource to ensure that it will validate against the
[AccessRegistryShape](#shexAccessRegistry), and contain only
conformant instances of the [AccessGrantTree](#treeAccessGrant).

<pre highlight="turtle" id="treeAccessRegistry">
<#access-registry-tree>
  a st:ShapeTree;
  st:expectsType st:ShapeTreeContainer ;
  st:validatedBy &lt;ecos#AccessRegistryShape&gt; ;
  st:contains <#access-grant-tree> ,
              st:AllowNone .
</pre>

### Access Grant ### {#datamodel-access-grant}

Each <dfn>Access Grant</dfn> represents access granted to one recipient; the
[=Access Grant Subject=], based on access criteria detailed in one or more
[=Prepared Access Need Groups=]. Access is granted to registered data in
[=Data Registries=], identified by [=Data Grants=] linked to the
[=Access Grant=].

<table class="classinfo data" align="left" id="classAccessGrant">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [AccessGrant](ecosystem.ttl#AccessGrant)
        a rdfs:subClassOf [[#reg-model|Registration]]
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>registeredBy</td>
      <td>Registration</td>
      <td>Agent</td>
      <td>[=Agent=] that registered the [=Access Grant=]</td>
    </tr>
    <tr>
      <td>registeredWith</td>
      <td>Registration</td>
      <td>Application</td>
      <td>[=Application=] used to create the [=Access Grant=]</td>
    </tr>
    <tr>
      <td>registeredAt</td>
      <td>Registration</td>
      <td>xsd:dateTime</td>
      <td>Date and time the [=Access Grant=] was created</td>
    </tr>
    <tr>
      <td>hasAccessGrantSubject</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>AccessGrantSubject</td>
      <td>Links to one [=Access Grant Subject=] who was granted access.</td>
    </tr>
    <tr>
      <td>hasPreparedAccessNeedGroup</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>PreparedAccessNeedGroup</td>
      <td>Links to a [=Prepared Access Need Group=] associated with the Access Grant.</td>
    </tr>
    <tr>
      <td>hasDataGrant</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>DataGrant</td>
      <td>Links to a [=Data Grant=] associated with the Access Grant.</td>
    </tr>
  </tbody>
</table>

The [AccessGrantShape](#shexAccessGrant) is used to validate an instance
of the [AccessGrant](#classAccessGrant) class.

<pre highlight="turtle" id="shexAccessGrant">
<#AccessGrantShape> {
  a [ eco:AccessGrant ] ;
  eco:registeredBy IRI ;
  eco:registeredWith IRI? ;
  eco:registeredAt xsd:dateTime ;
  eco:accessGrantSubject @AccessGrantSubject ;
  eco:hasPreparedAccessNeedGroup @PreparedAccessNeedGroupShape+ ;
  eco:hasDataGrant @DataGrantShape+
}
</pre>

The [AccessGrantTree](ecosystem.tree#access-grant-tree) is assigned to a
resource via the [AccessRegistryTree](#treeAccessRegistry), and ensure
that the assigned resource will validate against the
[AccessGrantShape](#shexAccessGrant).

<pre highlight="turtle" id="treeAccessGrant">
<#access-grant-tree>
  a st:ShapeTree;
  st:expectsType st:ShapeTreeResource ;
  st:validatedBy &lt;ecos#AccessGrantShape&gt; ;
  st:matchesUriTemplate "{id}" .
</pre>

### Access Grant Subject ### {#datamodel-access-grant-subject}

An <dfn>Access Grant Subject</dfn> represents a unique combination of
who and what is being granted access. For example, it allows a single [=Agent=]
to be specified, or a given [=Agent=] using a given [=Application=].

<table class="classinfo data" align="left" id="classAccessGrantSubject">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>[AccessGrantSubject](ecosystem.ttl#AccessGrant)</th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>accessByAgent</td>
      <td>[AccessGrantSubject](#classAccessGrantSubject)</td>
      <td>Agent</td>
      <td>[=Agent=] being granted access</td>
    </tr>
    <tr>
      <td>accessByApplication</td>
      <td>[AccessGrantSubject](#classAccessGrantSubject)</td>
      <td>Application</td>
      <td>[=Application=] being granted access</td>
    </tr>
  </tbody>
</table>

The [AccessGrantSubjectShape](#shexAccessGrantSubject) is used to validate
an instance of the [AccessGrantSubject](#classAccessGrantSubject) class.

<pre highlight="turtle" id="shexAccessGrantSubject">
<#AccessGrantSubjectShape> {
  a [ eco:AccessGrantSubject ] ;
  eco:accessGrantSubjectAgent IRI? ;
  eco:accessGrantSubjectApplication IRI?
}
</pre>

### Data Grant ### {#datamodel-data-grant}

A <dfn>Data Grant</dfn> records a decision made by a
given [=Agent=] based upon [=Prepared Access Needs=] presented to them
for a given [=Data Registration=].

<table class="classinfo data" align="left" id="classDataGrant">
  <col>
  <colgroup span=2></colgroup>
  <col>
  <thead>
    <tr>
      <th colspan=4>
        [DataGrant](ecosystem.ttl#DataGrant)
      </th>
    </tr>
    <tr>
      <th>Property</th>
      <th>Domain</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasRegistration</td>
      <td>-</td>
      <td>DataRegistration</td>
      <td>[=Data Registration=] the [=Data Grant=] grant applies to</td>
    </tr>
    <tr>
      <td>registeredShapeTree</td>
      <td>-</td>
      <td>st:ShapeTree</td>
      <td>The [=shape tree=] registered at the target [=Data Registration=]</td>
    </tr>
    <tr>
      <td>satisfiesPreparedAccessNeed</td>
      <td>[DataGrant](#classDataGrant)</td>
      <td>PreparedAccessNeed</td>
      <td>Links to a [=Prepared Access Need=] satisfied by the [=Data Grant=]</td>
    </tr>
    <tr>
      <td>accessMode</td>
      <td>-</td>
      <td>acl:Read, acl:Write, acl:Control, acl:Append</td>
      <td>Union of access modes from [=Prepared Access Needs=] linked by
      satisfiesPreparedAccessNeed</td>
    </tr>
    <tr>
      <td>scopeOfDataGrant</td>
      <td>[DataGrant](#classDataGrant)</td>
      <td> eco:AllInstances, eco:InheritInstances,
      eco:SelectedInstances, eco:NoAccess</td>
      <td>Identifies the access scope of the [=Data Grant=]
        <ul>
          <li>eco:AllInstances - Scope includes
              access to all [=Registered Data Instances=] of the associated
              [=Data Registration=]</li>
          <li>eco:InheritInstances - Scope includes
              access to [=Registered Data Instances=] inherited by
              instances selected in the [=Data Grant=] linked via
              eco:inheritsFromDataGrant</li>
          <li>eco:SelectedInstances - Scope includes
              access only to those [=Registered Data Instances=] specifically
              selected by the [=Agent=]</li>
          <li>eco:NoAccess</li> - No access is granted
        </ul>
      </td>
    </tr>
    <tr>
      <td>inheritsFromDataGrant</td>
      <td>[DataGrant](#classDataGrant)</td>
      <td>[DataGrant](#classDataGrant)</td>
      <td>Identifies a [=Data Grant=] whose selected
      [=Registered Data Instances=] narrow the scope of instances to be
      presented by this grant.</td>
    </tr>
  </tbody>
</table>

The [DataGrantShape](#shexDataGrant) is used to
validate an instance of the [DataGrant](#classDataGrant)
class.

<pre highlight="turtle" id="shexDataGrant">
<#DataGrantShape> {
  a [ eco:DataGrant ] ;
  eco:hasRegistration IRI ;
  eco:registeredShapeTree IRI ;
  eco:satisfiesPreparedAccessNeed @PreparedAccessNeedShape+ ;
  eco:accessMode [ acl:Read acl:Write acl:Append acl:Control ]+ ;
  eco:scopeOfDataGrant [ eco:SelectedInstances eco:AllInstances eco:InheritInstances eco:NoAccess ] ;
  eco:inheritsFromDataGrant @DataGrantShape*
}
</pre>

## Resource Hierarchy ## {#access-hierarchy}

<table class="data tree" align="left">
  <col>
  <col>
  <col>
  <col>
  <thead>
    <tr>
      <th>Resource</th>
      <th>Class</th>
      <th>Shape</th>
      <th>Shape Tree</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>`/registries/#registrar`</td>
      <td>[Registrar](#)</td>
      <td>[RegistrarShape](#)</td>
      <td>[RegistrarTree](#)</td>
    </tr>
    <tr>
      <td>`-- access#set`</td>
      <td>[AccessRegistrySet](#classAccessRegistrySet)</td>
      <td>[AccessRegistrySetShape](#shexAccessRegistrySet)</td>
      <td>[AccessRegistrySetTree](#treeAccessRegistrySet)</td>
    </tr>
    <tr>
      <td>`/access/#registry`</td>
      <td>[AccessRegistry](#classAccessRegistry)</td>
      <td>[AccessRegistryShape](#shexAccessRegistry)</td>
      <td>[AccessRegistryTree](#treeAccessRegistry)</td>
    </tr>
    <tr>
      <td>`-- c482f931...630e5ab0#grant`</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>[AccessGrantShape](#shexAccessGrant)</td>
      <td>[AccessGrantTree](#treeAccessGrant)</td>
    </tr>
    <tr>
      <td>`-- e0983a7e...88c387ea#grant`</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>[AccessGrantShape](#shexAccessGrant)</td>
      <td>[AccessGrantTree](#treeAccessGrant)</td>
    </tr>
    <tr>
      <td>`-- eddf13d6...7f4962c5#grant`</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>[AccessGrantShape](#shexAccessGrant)</td>
      <td>[AccessGrantTree](#treeAccessGrant)</td>
    </tr>
    <tr>
      <td>`-- a990c1b9...c041eb74#grant`</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>[AccessGrantShape](#shexAccessGrant)</td>
      <td>[AccessGrantTree](#treeAccessGrant)</td>
    </tr>
    <tr>
      <td>`-- 265ef957...6689aee7#grant`</td>
      <td>[AccessGrant](#classAccessGrant)</td>
      <td>[AccessGrantShape](#shexAccessGrant)</td>
      <td>[AccessGrantTree](#treeAccessGrant)</td>
    </tr>
  </tbody>
</table>

The [=Access Registry Set=] and the [=Access Registry=] MAY or MAY NOT
be on the same [=pod=].

[=Access Registry Set=] and [=Access Registry=] resources MAY use any
resource or subject names.

[=Access Grants=] MUST use \[UUIDs](https://www.ietf.org/rfc/rfc4122.txt)
for resource names.

## Operations ## {#access-operations}

### Present Grant ### {#access-present}

Input: Grant

Output: Grant

Note: This will fetch existing Dgrants from registry where applicable

1. Let `GROUP` [eco:needGroupLabel](ecosystem.ttl#needGroupLabel) be the
    object value of `GDEC`
    <a href="http://www.w3.org/2004/02/skos/core#prefLabel" class="vocab">
    skos:prefLabel</a>.
1. Let `GROUP` [eco:needGroupExplanation](ecosystem.ttl#needGroupExplanation)
    be the object value of `GDEC`
    <a href="http://www.w3.org/2004/02/skos/core#definition" class="vocab">
    skos:definition</a>.

Issue: Must also deal with case when returning to an Access Need Group
and disabling access, which would mean all DGRANTS get so to NoAccess.

Issue: Must handle apppend on contained cases and set the scope appropriately

Issue: Must also ensure that we are loading the original GRANT to pickup
where we left off.

Issue: Must also handle the case when the origin access need group has
been expanded (optionally show that to the user and the authorization
options)

### Record Grant ### {#access-record}

This operation is called based on decisions an [=Agent=] has made on one or
more [=Prepared Access Need Groups=] for a given [=Authorization Subject=],
which are recorded in the form of [=Data Grants=].

#### Inputs #### {#record-inputs}

* Let `GRANT` be an [=Access Grant=] linked to any new or updated
    [=Prepared Access Need Groups=] and [=Data Grants=]
    for a given [=Authorization Subject=]

Note: If the [=Authorization Subject=] has already received an [=Access Grant=],
it will already have a `GRANT` record in the [=Access Registry=]. When
`GRANT` is passed as input here, it must be based on an updated set of the
stored [=Prepared Access Need Groups=] and [=Data Grants=].

#### Outputs #### {#record-outputs}

* Let `GRANT` be an [=Access Grant=] that has been stored in the
    [=Access Registry=] and had the relevant permissions applied.

#### Operation Details #### {#record-details}

Assert: It is the responsibility of the caller to guaranteee that
[=Prepared Access Need Groups=] and [=Data Grants=] linked to
to `GRANT` are synchronized based on the [=Agent's=]
most recent applied choices across all linked [=Prepared Access Need Groups=].

1. Let `ACCESS` be the [=Access Registry=] instance
1. Let `PGROUPS` be the [=Prepared Access Need Groups=] linked to `GRANT`
    via `GRANT hasPreparedAccessNeedGroup`
1. Let `DGRANTS` be the [=Data Grants=] linked to `GRANT`
    via `GRANT hasDataGrant`
1. For each [=Prepared Access Need Group=] `PGROUP` in `PGROUPS`:
    2. For each [=Prepared Access Need=] `NEED` in `PGROUP` traversed via
        `NEED skos:narrower` or `NEED referencesPreparedAccessNeed`:
        1. Let `NDGRANT` be the [=Data Grant=] associated with
            `NEED` via `NEED hasDataGrant`
            1. Error if `NDGRANT` is missing
            1. Error if `NDGRANT satisfiesPreparedAccessNeed` doesn't link to `NEED`
            2. Error if `eco:RegisteredShapeTree` is not the same in `NDGRANT` and `NEED`
2. For each [=Data Grant=] `DGRANT` in `DGRANTS`
    3. Let `NEEDS` be all [=Prepared Access Needs=] across `PGROUPS`
    4. Let `DGNEEDS` be all [=Prepared Access Needs=] linked to `DGRANT` via
        `DGRANT satisfiesPreparedAccessNeed`
    4. Error if `DGNEEDS` is not in `NEEDS`
    5. Error if `DGNEEDS` is empty
    6. Error if `DGRANT` access modes are not an exact union of `DGNEEDS accessMode` values
        when `DGRANT scopeOfDataGrant` is not `eco:NoAccess`
3. Call [[#access-applyperms]] with `GRANT`
4. Store `GRANT` in `ACCESS`
    1. `GRANT` must be added to `ACCESS`, conforming to the assigned
        [ecot:access-grant-tree](ecosystem.tree#access-grant-tree)
    1. `GRANT` must conform to
        [ecos:accessGrantShape](ecosystem.shex#accessGrantShape) per
        [ecot:access-grant-tree](ecosystem.tree#access-grant-tree)
    1. Add `GRANT` to the graph of `ACCESS` via `ACCESS hasRegistration`
4. Return `GRANT`

Issue: Need to properly factor in multi-pod scenarios. Must identify the
proper access registry to store things in based on the data registration, which
means pods will also need to be registered.

### Apply Permissions ### {#access-applyperms}

#### Inputs #### {#applyperms-inputs}

* Let `GRANT` be an [=Access Grant=] linked to any new or updated
    [=Prepared Access Need Groups=] and [=Data Grants=]
    for a given [=Authorization Subject=]

#### Outputs #### {#applyperms-outputs}

* Let `GRANT` be an [=Access Grant=] that has had the relevant permissions applied.

#### Operation Details #### {#applyperms-details}

1. Let `DGRANTS` be the [=Data Grants=] linked to `GRANT`
    via `GRANT hasDataGrant`
1. For each [=Data Grant=] `DGRANT` in `GRANTS`
    1. Let the [=Data Registration=] linked via `DGRANT hasRegistration` be `DREG`
    1. If `DGRANT scopeOfDataGrant` includes `eco:NoAccess`
        1. Ignore any other scopes linked via `DGRANT scopeOfDataGrant`
        1. Let `ACL` be the [=ACL Resource=] directly associated with `DREG`
        1. Let `STATEMENTS` be any [=Authorization Statements=] in `ACL` directly
            associated with `GRANT accessGrantSubject`.
        1. For each `STATEMENT` in `STATEMENTS`
            1. Remove [=Authorization Subject=] from `STATEMENT`
            2. Remove `STATEMENT` if there are no remaining [=Authorization Subjects=]
    1. If `DGRANT scopeOfDataGrant` includes `eco:AllInstances`
        1. Error if `eco:AllInstances` is not the only scope associated via
            `DGRANT scopeOfDataGrant`
        1. Let `ACL` be the [=ACL Resource=] directly associated with `DREG`
        1. Let `STATEMENTS` be any [=Authorization Statements=] in `ACL` directly
            associated with `GRANT accessGrantSubject`.
        1. For each `STATEMENT` in `STATEMENTS`
            1. Remove [=Authorization Subject=] from `STATEMENT`
            1. Remove `STATEMENT` from `ACL` if there are no
                remaining [=Authorization Subjects=] in `STATEMENT`
        1. Add a new [=Authorization Statement=] `NEWSTATEMENT` to `ACL`
            1. Set `NEWSTATEMENT` [=Authorization Subject=] to
                `GRANT accessGrantSubject`.
            2. Set the [=access modes=] for `NEWSTATEMENT` to
                the [=access modes=] linked via `DGRANT accessMode`
                such that all [=Registered Data Instances=] in `REG` inherit
                those [=access modes=]
    1. If `DGRANT scopeOfDataGrant` includes ONLY `eco:InheritInstances`
        1. Let `IDGRANT` be the inherited [=Data Grant=]
        1. Error if `DGRANT inheritsFromDataGrant` is missing
        1. Error if `IDGRANT eco:RegisteredShapeTree` does not have a reference
            to `DGRANT eco:registeredShapeTree` via `st:references`
        1. Let `ACL` be the [=ACL Resource=] directly associated with `DREG`
        1. Let `STATEMENTS` be any [=Authorization Statements=] in `ACL` directly
            associated with `GRANT accessGrantSubject`.
        1. For each `STATEMENT` in `STATEMENTS`
            1. Remove [=Authorization Subject=] from `STATEMENT`
            1. Remove `STATEMENT` from `ACL` if there are no
                remaining [=Authorization Subjects=] in `STATEMENT`
        1. Add a new [=Authorization Statement=] `NEWSTATEMENT` to `ACL`
            1. Set `NEWSTATEMENT` [=Authorization Subject=] to
                `GRANT accessGrantSubject`.
            1. Set the [=access modes=] for `NEWSTATEMENT` to
                the [=access modes=] linked via `DGRANT accessMode`
                such that all [=Registered Data Instances=] in `REG` inherit
                those [=access modes=], with the following condition:
                    1. Access will only be granted to
                        [=Registered Data Instances=] when a link exists between
                        `IDGRANT eco:registeredShapeTree` and
                        `DGRANT eco:registeredShapeTree`.
                    1. The predicate of the link must be the same as the
                        property detailed in `st:traverseViaShapePath`, in the
                        `st:references` from `IDGRANT eco:registeredShapeTree`
    1. If `DGRANT scopeOfDataGrant` includes `eco:InheritInstances` AND `eco:SelectedInstances`
        1. Error if any other scopes are associated via `DGRANT scopeOfDataGrant`
        1. Error if `DGRANT inheritsFromDataGrant` is missing
        1. Error if `IDGRANT eco:RegisteredShapeTree` does not have a reference
            to `DGRANT eco:registeredShapeTree` via `st:references`
        1. Use instructions for `eco:SelectInstances`
    1. If `DGRANT scopeOfDataGrant` includes `eco:SelectedInstances`
        1. Let `INSTANCES` be the [=Registered Data Instances=] linked via
            `DGRANT eco:hasRegisteredDataInstance`
        1. Error if there are no `INSTANCES`
        1. For each `INSTANCE` in `INSTANCES`
          1. Error if `INSTANCE` is missing
          1. Let `ACL` be the [=ACL Resource=] directly associated with `INSTANCE`
          1. Let `STATEMENTS` be any [=Authorization Statements=] in `ACL` directly
              associated with `GRANT accessGrantSubject`
          1. For each `STATEMENT` in `STATEMENTS`
              1. Remove [=Authorization Subject=] from `STATEMENT`
              1. Remove `STATEMENT` from `ACL` if there are no
                  remaining [=Authorization Subjects=] in `STATEMENT`
          1. Add a new [=Authorization Statement=] `NEWSTATEMENT` to `ACL`
              1. Set `NEWSTATEMENT` [=Authorization Subject=] to
                  `GRANT accessGrantSubject`.
              1. Set the [=access modes=] for `NEWSTATEMENT` to
                  the [=access modes=] linked via `DGRANT accessMode`
              1. If `INSTANCE` is a container, ensure all [=resources=] in the
                  container are set to inherit those [=access modes=]

Issue: Deal with cases when the data registration doesn't exist yet

Issue: Append mode for AllInstances needs to be specially handled, and may
require an additional attribute specified in the requested [=Access Needs=]

Exchanging Access Information {#exchanging}
=====================

## Patterns for making requests and getting access ## {#exchanging-protocol}

### Access for other agents / people ### {#exchanging-agentpattern}

TODO

### Access for piloted applications ### {#exchanging-pilotpattern}

TODO

### Access for services (autonomous) ### {#exchanging-servicepattern}

TODO

### Communicating access grants ### {#exchanging-communicating}

TODO


Trusted Agents {#trusted}
=====================

A [=trusted Agent=] is an application that a [=Agent=] trusts
to perform actions for them with elevated privilege. They can be
trusted to help a [=Agent=] to make smart decisions related to
their data.

There's no limit to what a trusted agent can
assist with, but [[#appreg|registering applications]] and authorizing access to
data are two critical operations covered in this proposal.

A trusted [=application registration agent=] helps the [=Agent=]
make smart decisions about the applications they choose to utilize, and
ensure they get provisioned appropriately.

A trusted agent for data authorization is needed in cases where the resource
controller wishes to grant limited access to data in her Pod to another
[=authenticated agent=] or [=user-piloted application=], but needs
assistance to determine what access is needed, and help to provision
that access.

There are three typical patterns to interact with a trusted agent;
*Embedded*, *Synchronous*, and *Asynchronous*.

The **Embedded pattern** is employed when the application in question has full
control privileges, and the trusted agent capabilities can
be executed directly. An example of an application that could fall into
this category would be a Pod management application installed by default
by the user’s Pod provider.

The **Synchronous pattern** utilizes a web-based redirect flow much like an
OAuth2 grant flow. The user is redirected to the trusted agent URL, with
a callback parameter provided as part of the request. When the
trusted agent is finished, it sends the user back to the provided
callback URL. This is an excellent pattern for application registration
and data authorization.

The **Asynchronous pattern** utilizes an event based model, where a message is
sent to the Trusted Agent through some mechanism (direct, pubsub, etc).
This flow is most typical for server-side/bot applications or any piloted
clients that can make use of asynchronous notification processing.

A given trusted agent may employ one or more of these patterns.

Client Identification {#client}
=====================

Throughout this proposal, we see cases where Alice compartmentalizes access
to her data based on who or what is access it - the [=authenticated agent=].
In certain cases, we also limit access based on the application in use
by Alice - the
[=user-piloted application=].

We utilize a new optional predicate in an [=acl resource=] statement to
restrict access to permitted [=user-piloted applications=], identified by their
[=ApplicationIDs=].

Limiting access to data based on
the [=user-piloted application=] in use is only reliable in certain
instances when the [=application=] can be identified with confidence.

## Identifying client applications ## {#client-id}

For identification purposes, client [=applications=] in use across the world
today fall into two buckets; *strongly identifiable* and *weakly identifiable*.

**Strongly identifiable clients** can be identified by 3rd parties independently
from their user/controller. Only [=server-side applications=] are
strongly identifiable. As confidential clients, they can keep secrets
and can present attestations and third-party credentials
via DNS / domain certificates.

**Weakly identifiable clients** include in-browser JS apps and native desktop
or mobile applications. They are considered weakly identifiable because they
are not able to keep secrets on an instance level. They are often referred to
as public clients. Native apps should be strongly-identifiable in theory
(since they are able to keep secrets on an instance level), but not in
practice because the OS manufacturers do not make their trust
infrastructure available. **Weakly identifiable clients are only strongly
identifiable to the user controlling them**.

## Limiting access by client application ## {#client-limit}

In the case of a strongly identifiable [=server-side application=],
the [=authenticated agent=] and the client application are the same. The client
application has its own [=identity=] that can be strongly authenticated. Alice
chooses which data that client application's identity can access, in the same
way that she chooses which data Bob can access.

In the case of [=user-piloted applications=], the ability for a Solid pod to
limit access to data by the client application in use is only as strong as
the trustworthiness of the user piloting that application, and their ability
to avoid using malicious applications. The [=ApplicationID=] can be manipulated
by the user in control of the app. This means that Alice can strongly control
the applications that she uses to compartmentalize her own data, but has
limited ability to control the applications that Bob uses to access the data
she shares with him.

Definitions {#definitions}
=====================

<b>All definitions as stated below should be considered in the context of
an interoperable [=ecosystem=] for [=Solid=], whether explicitly stated
or not.</b>

<dfn>Solid</dfn> is a protocol made up of a number of open web standards
aimed at decentralizing data on the web.

A Solid <dfn>pod</dfn> is a place for storing and accessing data via
the [=Solid=] protocol, with mechanisms for controlling who or what can
access that data.

An interoperable <dfn>ecosystem</dfn> is
a collection of [=Solid=] compatible [=applications=] developed by one or more
entities, used by a community of users, that can safely access and manipulate
the same kinds of data in [=pods=].

An <dfn>Agent</dfn> is a distinct individual, group, organization, or piece
of software with an identity that can be strongly authenticated. Represented
by the [eco:Agent](ecosystem.ttl#Agent) class. Validated by the
[ecos:AgentShape](ecosystem.shex#AgentShape). Associated with resources by the
[ecot:agent-tree](ecosystem.tree#agent-tree). A given [=Agent=] is considered
the [=resource controller=] for any [=registrations=] in their [=registries=].

An <dfn>Application</dfn> is a piece of software that interfaces with a
Solid pod, either as a [=server-side application=], or as a
[=user-piloted application=]. Represented by the
[eco:Application](ecosystem.ttl#Application) class. Validated by the
[ecos:ApplicationShape](ecosystem.shex#ApplicationShape).

A <dfn>server-side application</dfn> runs on a dedicated server. They may
also act as autonomous [=authenticated agents=].

A <dfn>user-piloted application</dfn> runs on a user's device, with the user
as the [=authenticated agent=]. They include in-browser javascript
applications, native desktop applications, and mobile applications.

An <dfn>identity</dfn> in Solid is a unique URI that can be dereferenced to
return an [=identity profile document=]. Compatible identity systems
include [=WebID=] and [=DID=].

An <dfn>identity profile document</dfn> is a linked data document obtained
by dereferencing the URI for a given [=identity=]. It provides information
that can be used to prove that a given [=agent=] controls the document.

An <dfn>authenticated agent</dfn> is an [=agent=] that has strongly
authenticated their [=identity=] by proving control of the
[=identity profile document=] via an authentication protocol such as
[[WEBID-OIDC]].

A <dfn>WebID</dfn> is a web resource at an HTTP URI which refers to an
[=agent=]. An [=identity profile document=] can be accessed by
dereferencing the WebID. [[WEBID]]

A <dfn>DID</dfn> is a URI that associates a DID subject (e.g. an [=agent=],
thing, data model, abstract entity, etc.) with a DID document,
equivalent to an [=identity profile document=], to allow trustable
interactions with that subject. [[DID]]

An <dfn>identity provider</dfn> furnishes an [=agent=] with authenticated
credentials that prove agent is who it says it is, across the web.

A <dfn>token</dfn> is used to make authenticated requests to the [=Solid=]
server for a given [=authenticated agent=].

An <dfn>ApplicationID</dfn> is a web resource at an HTTP URI uniquely associated
with a given [=application=]. For [=server-side applications=], it may also
serve as an [=identity=]. An [=application profile document=] can be
accessed by dereferencing the ApplicationID.

An <dfn>application profile document</dfn> is a linked data document
obtained by dereferencing the URI for a given [=ApplicationID=]. It contains
useful information about an application that can be employed in
various workflows including application registration and data authorization.

A <dfn>resource controller</dfn> is an [=authenticated agent=] with full
privileges and control over a given resource or set of resources.

An <dfn>acl resource</dfn> as defined by [[WAC]] may be directly
associated with a resource or indirectly associated with a resource
through inheritance. It determines which [=authorization subjects=] can
access a resource, and the modes of access they have for it.

An <dfn>access mode</dfn> denotes operations (e.g. read, write)
that a given [=authorization subject=] can perform on a resource.

An <dfn>authorization subject</dfn> is the target of a given authorization
statement in an [=acl resource=]. It is either an [=Agent=] (individual,
group, [=server-side application=]), a
[=User-Piloted Application=] in use by *any* [=Agent=], or a combination of
a specific [=Agent=] using a specific [=User-Piloted Application=].

An <dfn>authorization statement</dfn> is ...

A <dfn>trusted agent</dfn> is any [=application=] that a
[=Agent=] trusts to perform actions for them. These
actions typically require some leve

An <dfn>application registration agent</dfn> is a type of [=trusted agent=]
that an [=Agent=] uses to register and manage applications that
interface with their [=pod=].

A <dfn>data authorization agent</dfn> is a type of [=trusted agent=]
that assists a [=Agent=] with the managing the data
in their [=Data Registries=], and authorizing access to it from other
[=authorization subjects=].

A <dfn>shape</dfn> provides a schema that RDF data graphs must meet in order
to be considered conformant. A shape associated with a given resource in a
[=pod=] ensures that any data stored in that resource must conform to the
associated shape. Shape languages include [[SHEX]] and [[SHACL]].

A <dfn>shape tree</dfn> defines a prospective tree of related resources
which can be read and written by applications. The shape tree associates
each of these resources with a shape. This allows one to treat a set of
related resources as a single grouping, and apply that to a range of
operations including access control, data organization, data validation,
and data migration. [[SHAPETREES]]

A <dfn>Registrar</dfn> for a given [=Agent=] provides [=Registries=],
organized in [=Registry Sets=]. Represented by the
[eco:Registrar](ecosystem.ttl#Registrar) class. Validated by the
[ecos:RegistrarShape](ecosystem.shex#RegistrarShape). Associated with
resources by the
[ecot:registrar-shape-tree](ecosystem.tree#registrar-shape-tree).

A <dfn>Registry Set</dfn> is a collection of one or more registries of a
specific type, including [=Application Registries=], Data Registries,
Access Registries, and Remote Registries. Represented by the
[eco:RegistrySet](ecosystem.ttl#RegistrySet) class.

A <dfn>Registry</dfn> is a collection of [=Registrations=] stored in a
specific location in a [=pod=]. It provides a place where an [=Agent=]
can register, store, and lookup essential data needed to participate in
the [=ecosystem=]. Represented by the
[eco:Registry](ecosystem.ttl#Registry) class.

A <dfn>Registration</dfn> is the basic data unit of any [=Registry=].

An <dfn>Application Registry Set</dfn> is a [=Registry Set=] specifically
made up of [=Application Registries=]. Represented by the
[eco:ApplicationRegistrySet](ecosystem.ttl#ApplicationRegistySet) class.
Validated by the
[ecos:ApplicationRegistrySetShape](ecosystem.shex#RegistrySetShape).
Associated with resources by the
[ecot:application-registry-set-tree](ecosystem.tree#application-registry-set-tree).

An <dfn>Application Registry</dfn> is a collection of
[=Application Registrations=] stored in a specific location in a [=pod=].
Represented by the
[eco:ApplicationRegistry](ecosystem.ttl#ApplicationRegistry) class.
Validated by the
[ecos:ApplicationRegistryShape](ecosystem.shex#ApplicationRegistryShape).
Associated with resources by the
[ecot:application-registry-tree](ecosystem.tree#application-registry-tree).

An <dfn>Application Registration</dfn> provides the [=Agent=]
with a place to maintain metadata, state, preferences, and
other application-specific data associated with a given [=Application=] they
have elected to use. Represented by the
[eco:ApplicationRegistration](ecosystem.ttl#ApplicationRegistration) class.
Validated by the
[ecos:ApplicationRegistrationShape](ecosystem.shex#ApplicationRegistrationShape).
Associated with resources by the
[ecot:application-registration-tree](ecosystem.tree#application-registration-tree).

A <dfn>Data Registry Set</dfn> is a [=Registry Set=] specifically made up of
[=Data Registries=]. Represented by the
[eco:DataRegistrySet](ecosystem.ttl#DataRegistrySet) class.
Validated by the
[ecos:DataRegistrySetShape](ecosystem.shex#DataRegistrySetShape).
Associated with resources by the
[ecot:data-registry-set-tree](ecosystem.tree#data-registry-set-tree).

A <dfn>Data Registry</dfn> is a collection of [=Data Registrations=], each
representing a unique type of data, stored in a specific location in a
Solid [=pod=]. Represented by the
[eco:DataRegistry](ecosystem.ttl#DataRegistry) class.
Validated by the
[ecos:DataRegistryShape](ecosystem.shex#DataRegistryShape).
Associated with resources through the
[ecot:data-registry-tree](ecosystem.tree#data-registry-tree).

A <dfn>Data Registration</dfn> provides the [=Agent=] with a place to store
[=Registered Data Instances=] of a particular type, conforming to a
given [=shape tree=]. Represented by the
[eco:DataRegistration](ecosystem.ttl#DataRegistration) class.
Validated by the
[ecos:DataRegistrationShape](ecosystem.shex#DataRegistrationShape).
Associated with resources through the
[ecot:data-registration-tree](ecosystem.tree#data-registration-tree).

A <dfn>Registered Data Instance</dfn> is a unique, stored instance of a
particular type of data conforming to a given [=shape tree=]. Each registered
data instance is contained within a given [=Data Registration=].

Use Case Environment {#environment}
=====================

## People ## {#people}

### Alice ### {#alice}

<table>
  <tbody>
    <tr>
      <td><th>Alice's Pod URL</th></td>
      <td>https://alice.pod.example</td>
    </tr>
    <tr>
      <td><th>Alice's WebID</th></td>
      <td>https://alice.pod.example/profile/id#me</td>
    </tr>
  </tbody>
</table>

#### Alice's Profile Document #### {#alice-profile}

Issue: Need to provide more detail around *how* applications, data, access,
remote registry items get organized into different registries with a set along
with use cases.

<figure>
  <figcaption>Alice’s identity profile document at
  https://alice.pod.example/id</figcaption>
  <pre highlight="turtle">
  @prefix solid: &lt;http://www.w3.org/ns/solid/terms#&gt; .
  @prefix eco: &lt;http://www.w3.org/ns/solid/ecosystem#&gt; .

  <#me>
      a eco:Agent;
      eco:hasRegistrar &lt;https://alice.pod.example/registries/#registrar&gt; ;
      # Trusted Agents
      eco:trustsForApplicationRegistration &lt;https://trusted.example/ar/&gt; ;
      # Notification Endpoints
      eco:hasAccessInbox &lt;https://alice.pod.example/access/inbox&gt; .
      # Identity Provider
      solid:oidcIssuer &lt;https://idp.example&gt; ;
  </pre>
</figure>

#### Alice's Registrar #### {#alice-registrar}

<figure>
  <figcaption>Alice’s registrar instance at
  https://alice.pod.example/registries/application#set</figcaption>
  <pre highlight="turtle">
  <#registrar>
    a eco:Registrar;
    eco:hasApplicationRegistrySet &lt;https://alice.pod.example/registries/application#set&gt; ;
    eco:hasDataRegistrySet &lt;https://alice.pod.example/registries/data#set&gt; .
  </pre>
</figure>

#### Alice's Application Registry Set #### {#alice-appregset}

<figure>
  <figcaption>Alice’s application registry set instance at
  https://alice.pod.example/registries/application#set</figcaption>
  <pre highlight="turtle">
  <#set>
    a eco:ApplicationRegistrySet;
    eco:hasApplicationRegistry &lt;https://alice.pod.example/applications/#registry&gt; ,
                               &lt;https://alice.otherpod.example/applications/#registry&gt; .
  </pre>
</figure>

#### Alice's Application Registry #### {#alice-appregistry}

<figure>
  <figcaption>Alice's application registry instance at
  https://alice.pod.example/applications/#registry</figcaption>
  <pre highlight="turtle">
  <#registry>
    a eco:ApplicationRegistry ;
    eco:hasRegistration &lt;https://alice.pod.example/applications/70e9249113f8aef095626980e82f13833f24a902571502ef726b4d7e69739ba3/#registration&gt; .
  </pre>
</figure>

Note that `https://alice.pod.example/applications/` is a container,
and #registry is stored in the RDF graph of the container resource.

#### Alice's Application Registration for Nevernote #### {#alice-appregnevernote}

<figure>
  <figcaption>Alice’s application registration instance for NeverNote at
  https://alice.pod.example/applications/70e9249113f8aef095626980e82f13833f24a902571502ef726b4d7e69739ba3/#registration</figcaption>
  <pre highlight="turtle">
  <#registration>
    a eco:ApplicationRegistration ;
    eco:registeredBy &lt;https://alice.pod.example/profile/id#me&gt; ;
    eco:registeredWith &lt;https://trusted.example/ar&gt; ;
    eco:registeredApplication &lt;https://nevernote.example/id#agent&gt; ;
    eco:registeredAt "2020-04-04T20:15:47.000Z"^^xsd:dateTime .
  </pre>
</figure>

Note that
`https://alice.pod.example/applications/70e9249113f8aef095626980e82f13833f24a902571502ef726b4d7e69739ba3/`
is a container, and #registration is stored in the RDF graph of the
container resource.

## Applications ## {#applications}

### NeverNote ### {#nevernote}

<table>
  <tbody>
    <tr>
      <td><th>Application URL</th></td>
      <td>https://nevernote.example</td>
    </tr>
    <tr>
      <td><th>Application ID (AppID)</th></td>
      <td>https://nevernote.example/id#agent</td>
    </tr>
    <tr>
      <td><th>SHA-256 Hash of AppID</th></td>
      <td>70e9249113f8aef095626980e82f13833f24a902571502ef726b4d7e69739ba3</td>
    </tr>
  </tbody>
</table>

#### NeverNote's Profile Document #### {#nevernote-profile}

<figure>
  <figcaption>Contents of NeverNote’s Profile Document at
  https://nevernote.example/id#agent</figcaption>
  <pre highlight="turtle">
  @prefix solid: &lt;http://www.w3.org/ns/solid/terms#&gt; .
  @prefix eco: &lt;http://www.w3.org/ns/solid/ecosystem#&gt; .
  @prefix acl: &lt;http://www.w3.org/ns/auth/acl&gt; .

  <#agent>
      # this is an application, not a person
      a eco:Application;
      # redirect to this URL after going through authorization agent workflow
      eco:authorizationCallback &lt;https://nevernote.example/data-authorization&gt; ;
      # redirect to this URL after going through application registration
      # agent workflow
      eco:applicationRegistrationCallback &lt;https://nevernote.example/app-registration&gt; ;

  # Declaration of the type of access this application needs
  # UUID randomly generated for subject value
  <#33116309-1667-4a7b-a91f-4dbf177e3f95>
      a eco:accessNeed;
      # Access needs related to notebook shape trees
      eco:shapetree &lt;https://shapetrees.example/commonnote#notebook&gt;
      # Request permission create new notebook shape trees
      eco:shapetreeCreate true;
      # Request permission to read and write created notebook shape trees
      eco:shapetreeCreateAccess [ acl:Read, acl:Write ];
      # Request access to any existing notebook shape trees
      eco:shapetreeExistingAccess true;
      # Request permission to read and write existing notebook shape trees
      eco:shapetreeExistingAccess [ acl:Read, acl:Write ].

  <#75054942-b8b4-4e3a-84e4-7b564ca1ae7a>
      a eco:accessNeed;
      eco:shapetree &lt;https://shapetrees.example/commonnote#note&gt;;
      eco:shapetreeCreate true;
      eco:shapetreeCreateAccess [ acl:Read, acl:Write ] ;
      eco:shapetreeExistingAccess true;
      eco:shapetreeExistingAccess [ acl:Read, acl:Write ].
  </pre>
</figure>

<pre class="biblio">
{
  "problems-and-goals": {
    "href": "https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md",
    "title": "Problems and Goals for Interoperability, Collaboration, and Security in a Solid Pod",
    "authors": [
      "Justin Bingham",
      "Eric Prud'hommeaux",
      "Jamie Fiedler",
      "Josh Collins"
    ]
  },
  "shapetrees": {
    "href": "https://shapetrees.github.io/specification/primer",
    "title": "Shape Trees",
    "authors": [
      "Justin Bingham",
      "Eric Prud'hommeaux",
      "Jamie Fiedler",
      "Josh Collins"
    ]
  },
  "wac": {
    "href": "https://solid.github.io/specification/wac/",
    "title": "Web Access Control"
  },
  "webid": {
    "href": "https://www.w3.org/2005/Incubator/webid/spec/identity/",
    "title": "WebID 1.0",
    "authors": [
      "Tim Berners-Lee",
      "Henry Story",
      "Andrei Sambra"
    ]
  },
  "did": {
    "href": "https://www.w3.org/TR/did-core/",
    "title": "Decentralized Identifiers (DIDs) v1.0",
    "authors": [
      "Drummond Reed",
      "Manu Sporney",
      "Dave Longley",
      "Christopher Allen",
      "Ryan Grant",
      "Markus Sabadello"
    ]
  },
  "shex": {
    "href": "http://shex.io/shex-semantics/index.html",
    "title": "Shape Expressions Language 2.1",
    "authors": [
      "Eric Prud'hommeaux",
      "Iovka Boneva",
      "Jose Emilio Labra Gayo",
      "Gregg Kellogg"
    ]
  },
  "shacl": {
    "href": "https://www.w3.org/TR/shacl/",
    "title": "Shapes Constraint Language (SHACL)",
    "authors": [
      "Holger Knublauch",
      "Dimitris Kontokostas"
    ]
  },
  "webid-oidc": {
    "href": "https://github.com/solid/webid-oidc-spec",
    "title": "WebID-OIDC Authentication Specification",
    "authors": [
      "Dmitri Zagidulin"
    ]
  }
}
</pre>
