sequenceDiagram
    autonumber
    participant App as Application (Client)
    participant OPAA as Alice's OIDC Provider & Authorization Agent
    participant AppID as Application's WebID Document
    participant WebID as Alice's WebID Document
    participant Pod as ACME's Pod
    note over App: 👩 Alice enters her WebID
    App ->> WebID: Resolve Alice's WebID
    WebID ->> App: Alice's WebID Document
    note over App: Discovers Alice's OIDC Provider and Authorization Agent from WebID Document
    App -->> OPAA: Initiate Solid-OIDC via redirect
    opt No active session with OP
    note over OPAA: 👩 Alice authenticates with OP
    end
    opt No existing registration
    note over OPAA: Creates Application Registration
    end
    OPAA ->> AppID: Resolve Application's WebID
    AppID ->> OPAA: Application's WebID Document
    note over OPAA: Authorization Agent finds Access Needs in Application's WebID Document
    note over OPAA: 👩 Alice grants access via consent screen based on Access Needs
    note over OPAA: Authorization Agent records Access Grants and updates Application Registration
    OPAA -->> App: Redirect with authorization code
    App ->> OPAA: Exchanges code for ID Token and Access Token 🔑
    note over App: ⚠️ Application uses WebID from ID Token
    note over App: Application discovers its registration from ID Token
    App ->> OPAA: Fetch Application Registration 🔑
    OPAA ->> App: Application Registration
    App ->> OPAA: Fetch Access Receipt 🔑
    OPAA ->> App: Access Receipt
    opt data grants in separate resources
      loop for each data grant IRI
        App ->> OPAA: Fetch Data Grant 🔑
        OPAA ->> App: Data Grant
      end
    end
    opt live update
      note over App: 🔑 Application subscribes for live updates to its registration
    end
    App ->> Pod: Fetch Project 1 🔑
    Pod ->> App: Project 1 Document
