flowchart LR

  AliceProRegistry(["🗄️ Data Registry (Professional)"])
  AliceProProjects["📁 Projects 🌿"]
  AliceProTasks["📁 Tasks 🌿"]
  PAp1("📄 P-Ap-1")
  PAp2("📄 P-Ap-2")
  TAp1("📄 T-Ap-1")
  TAp2("📄 T-Ap-2")
  TAp3("📄 T-Ap-3")
  TAp4("📄 T-Ap-4")

  subgraph pro.alice.example
    AliceProRegistry -- :hasDataRegistration --> AliceProProjects
    AliceProProjects -- ldp:contains --> PAp1
    AliceProProjects -- ldp:contains --> PAp2
    AliceProRegistry -- :hasDataRegistration --> AliceProTasks
    AliceProTasks -- ldp:contains ---> TAp1
    AliceProTasks -- ldp:contains ---> TAp2
    AliceProTasks -- ldp:contains ---> TAp3
    AliceProTasks -- ldp:contains ---> TAp4
    PAp1 -- pm:hasTask --> TAp1
    PAp1 -- pm:hasTask --> TAp2
    PAp2 -- pm:hasTask --> TAp3
  end
