
<!-- Includes
  https://www.specref.org and
  https://drafts.csswg.org/biblio.ref
-->

<pre class=biblio>
{

  "WEBID": {
    "href": "https://www.w3.org/2005/Incubator/webid/spec/identity/",
    "title": "WebID 1.0",
    "authors": [
      "Tim Berners-Lee",
      "Henry Story",
      "Andrei Sambra"
    ]
  },

  "DID": {
    "href": "https://www.w3.org/TR/did-core/",
    "title": "Decentralized Identifiers (DIDs) v1.0",
    "authors": [
      "Drummond Reed",
      "Manu Sporney",
      "Dave Longley",
      "Christopher Allen",
      "Ryan Grant",
      "Markus Sabadello"
    ]
  },

  "OIDC": {
    "href": "https://openid.net/specs/openid-connect-core-1_0.html",
    "title": "OpenID Connect Core 1.0",
    "authors": [
      "N. Sakimura",
      "J. Bradley",
      "M. Jones",
      "B. de Medeiros",
      "C. Mortimore"
    ]
  },

  "DPOP": {
    "href": "https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop",
    "title": "OAuth 2.0 Demonstrating Proof-of-Possession at the Application Layer",
    "authors": [
      "D. Fett",
      "B. Campbell",
      "J. Braidley",
      "T. Lodderstedt",
      "M. Jones",
      "D. Waite"
    ]
  }

}
</pre>


<!--~~~~~~~~~~~~~~~-->
<!-- STYLE CHANGES -->
<!--~~~~~~~~~~~~~~~-->

<style>

.note,
.issue,
.example,
.assertion,
.advisement {
  font-size: 0.9em;
}

pre {
  font-size: .8em;
}

em.rfc2119 {
  text-transform: lowercase;
  font-variant: small-caps;
  font-style: normal;
  font-size: 18px;
  color: #900;
}
  
</style>