
<!--~~~~~~~~~~-->
<!-- METADATA -->
<!--~~~~~~~~~~-->

<pre class=metadata>

Title: Solid Application Interoperability: Agent-Specific Discovery
Shortname: SAI-ASD

Editor: Justin Bingham
Editor: Eric Prud'hommeaux
Editor: elf Pavlik

!Contributor: Wouter Termont

Group: w3c
Status: w3c/ED
Revision: 7

URL: https://solid.github.io/data-interoperability-panel/specification/
Repository: https://github.com/solid/data-interoperability-panel

Boilerplate: style-darkmode off
Markup Shorthands: markdown yes
Inline Github Issues: title
Max ToC Depth: 2

Complain About: accidental-2119 yes, broken-links no, missing-example-ids yes, mixed-indents yes

Text Macro: MUST <em class=rfc2119>MUST</em>
Text Macro: SHOULD <em class=rfc2119>SHOULD</em>
Text Macro: MAY <em class=rfc2119>MAY</em>

Text Macro: NONORM *This section is non-normative.*
Text Macro: DISPLAY *(Extra indentation and newlines are for display purposes only.)*

Text Macro: L &lt;
Text Macro: R &gt;

Text Macro: HTTP    <l>[[!RFC9110|HTTP]]</l>
Text Macro: LINKS   <l>[[!RFC8288|Web-Linking]]</l>
Text Macro: RDF     <l>[[!RDF11-CONCEPTS|RDF 1.1]]</l>
Text Macro: RDFMT   <l>[[!RDF11-MT|RDF 1.1 Semantics]]</l>
Text Macro: RDFS    <l>[[RDF-SCHEMA|RDFS]]</l>
Text Macro: OWL     <l>[[OWL2-SYNTAX|OWL]]</l>
Text Macro: PROF    <l>[[PROF|Solid WebID Profile]]</l>
Text Macro: TI      <l>[[TI|Type Indexes]]</l>
Text Macro: JSON-LD <l>[[JSON-LD11|JSON-LD]]</l>
Text Macro: OAUTH   <l>[[RFC6749|OAuth 2.0]]</l>
Text Macro: DCR     <l>[[RFC7591|Dynamic Client Registration]]</l>

Text Macro: S200    [:200:] <code>(OK)</code>
Text Macro: S201    [:201:] <code>(Created)</code>
Text Macro: S303    [:303:] <code>(See Other)</code>
Text Macro: S400    [:400:] <code>(Bad Request)</code>
Text Macro: S401    [:401:] <code>(Unauthenticated)</code>
Text Macro: S403    [:403:] <code>(Forbidden)</code>

Abstract: 

  This specification details how Agents can discover the Resource Discovery 
  Hub of an Entity, and how they can interact with it in order to find 
  Agent-Specific Resources related to that Entity.

Status Text: 
  
  This document was published by the Editor(s) for the [Solid Community
  Group](https://www.w3.org/community/solid/) as an Editor's Draft. The sections
  that have been incorporated have been reviewed following the [Solid
  process](https://github.com/solid/process). The information in this document
  is still subject to change. You are invited to
  [contribute](https://github.com/solid/data-interoperability-panel/issues) any
  feedback, comments, or questions you might have. Publication as an Editor's
  Draft does not imply endorsement by the W3C Membership. This is a draft
  document and may be updated, replaced or obsoleted by other documents at any
  time. It is inappropriate to cite this document as other than work in
  progress. This document was produced by a group operating under the [W3C
  Community Contributor License Agreement
  (CLA)](https://www.w3.org/community/about/process/cla/). A human-readable
  [summary](https://www.w3.org/community/about/process/cla-deed/) is available.

</pre>

<div boilerplate=copyright>
MIT License Copyright 2019 - 2021 W3C Solid Community Group
</div>


<!--~~~~~~~~~~~-->
<!-- MAIN TEXT -->
<!--~~~~~~~~~~~-->

<pre class=include>path: terms.bs</pre>
<pre class=include>path: intro.bs</pre>
<pre class=include>path: agent-manager.bs</pre>
<pre class=include>path: agent-registry.bs</pre>


<!--~~~~~~~~~~~~-->
<!-- APPENDICES -->
<!--~~~~~~~~~~~~-->

<h2 id=sec-diagrams class=no-num>Appendix A: Summary Sequence Diagram</h2>
<img class=sequence-diagram src="diagrams/agent-specific-discovery.seq.mmd.svg" />


<!--~~~~~~~~~~~~~~-->
<!-- BIBLIOGRAPHY -->
<!--~~~~~~~~~~~~~~-->

<pre class=include>path: biblio.bs</pre>