sequenceDiagram
    participant Projectron's ID Document
    participant Projectron
    participant Authorization Agent
    participant Alice's Pod
    participant Alice's Identity Provider
    participant Alice's Identity Document
    Note over Projectron: 1. 👩 Alice decides to use Projectron
    Note over Projectron: 2. 👩 Alice provides her Identity
    Note over Alice's Identity Document,Projectron: 3. Projectron discovers Alice's Authorization Agent and IdP in her Profile Document
    Projectron->>Authorization Agent: 4. Check for Application Registration
    Authorization Agent->>Projectron: 5. 401 Not Authorized
    Note over Projectron, Alice's Identity Provider: 6. Solid-OIDC steps (including redirect)
    Projectron->>Authorization Agent: 7. Check for Application Registration
    Note over Authorization Agent, Alice's Pod: 8. Searches for Application Registration
    Authorization Agent->>Projectron: 9. No Application Registration Found
    Projectron-->>Authorization Agent: 10. Redirects Alice to her Authorization Agent
    Note over Projectron's ID Document, Authorization Agent: 11. Discovers Access Needs and redirect_uri
    Note over Authorization Agent: 12. 👩 Alice revievs Projectron Access Needs
    Note over Authorization Agent: 13. 👩 Alice chooses scope of access for Projectron
    Note over Authorization Agent, Alice's Pod: 14. Record Access Authorization
    Note over Authorization Agent, Alice's Pod: 15. Create Application Registration
    Note over Authorization Agent, Alice's Pod: 16. Provide Access Grant
    Authorization Agent-->>Projectron: 17. Redirect Alice back to Projectron
    Projectron->>Authorization Agent: 18. Check for Application Registration
    Note over Authorization Agent, Alice's Pod: 19. Serches for Application Registration
    Authorization Agent->>Projectron: 20. Provide Application Registration
    Note over Projectron, Alice's Pod: 21. Fetch Access Grant and Data Grants
    Note over Projectron: 22. 🟢 Now can access all the data Alice authized it to access
