sequenceDiagram

    autonumber
    
    participant ID as Identity Document
    participant App as Client Application
    participant AM as Agent Manager
    participant AR as Agent Registration
    participant RE as Registration Endpoint
    
    Note over ID: <> foaf:primaryTopic <id> .
    
    App->>ID: GET <id>
    ID-->>App: 200 OK

    break No Agent Manager <br/> in Link header or Body
        Note over ID,App: Rely on Identity Document only
    end
    
    App->>AM: HEAD <agent-manager> <br/> Authorization: DPoP ...
    AM-->>App: 200 OK

    break No Agent Registration <br/> or Registration Endpoint<br/>in Link header or Body
        Note over App: Rely on Identity Document only
    end

    opt No Agent Registration but Registration Endpoint in Link or Body
        App->>+RE: POST <registration-endpoint> <br/> Authorization: DPoP ... 
        Note over App,RE: Interactive sequence in which Agent Registration is created
        RE-->>-App: 201 Created <br/> Location: <agent-registration>
    end

    App->>AR: GET <agent-registration> <br/> Authorization: DPoP ...
    AR-->>App: 200 OK
    Note over App: Rely on both Identity Document <br/> and Agent Registration


