sequenceDiagram

    autonumber
    
    participant ID as Identity Document
    participant App as Client Application
    participant RDH as Agent Manager
    participant AR as Agent-Specific Resource
    participant ART as Access Request Target
    
    Note over ID: <> foaf:primaryTopic <id> .
    
    App->>ID: GET <id>
    ID-->>App: 200 OK

    break No RDH in Link header or body
        Note over ID,App: Rely on Identity Document only
    end
    
    App->>RDH: HEAD <rdh> <br/> Authorization: ...
    RDH-->>App: 200 OK

    break No ASR or ART in Link header or body
        Note over App: Rely on Identity Document only
    end

    opt No ASR but ART in Link or body
        App->>+ART: GET <art> <br/> Authorization: ... 
        Note over AR,ART: Agent Registration is created
        ART-->>-App: 201 Created <br/> Location: <asr>
    end

    App->>AR: GET <asr> <br/> Authorization: ...
    AR-->>App: 200 OK
    Note over App: Rely on both Identity Document <br/> and Agent-Specific Resource


