Agents {#agents}
=====================

<dfn>Agents</dfn> are the primary actors in an interoperable Solid [=ecosystem=].

An [=Agent=] is denoted by an [=identity=]. Dereferencing that [=identity=]
leads to [=identity profile document=], where a graph of useful information 
about the [=Agent=] can be found. This graph is used by the [=Agent=] 
as a starting point to look up their own data, as well as data that has 
been shared with them. 

The [=Agent=] graph in an [=identity profile document=] is designed to be 
publicly accessible, but many of the things the [=Agent=] links to are 
designed to be private, or accessible only by others they have authorized.

An [=Agent=] can dereference the [=identity=] of another [=Agent=] to obtain
the public information they need to interact with them.

[=Social Agents=] and [=Applications=] are specific types of [=Agents=]
denoted by this specification.

<div id="classAgent"></div>
