Agent Registrations {#ar}
=====================

[=Social Agents=] manage the other [=Social Agents=] and [=Applications=] they interact with
by registering these [=Agents=] in their [=Agent Registry=],
as defined in the [[sai-am|Agent Management]] specification.
The [=Agent Registry=] is linked to a [=Social Agent=] via their [=Registry Set=].

An <dfn>Agent Registry</dfn> is a collection of <dfn>Agent Registrations</dfn>. 
This specification distinguishes between [=Social Agent Registrations=] and [=Application Registrations=]

<p id=classSocialAgentRegistration>
Each [=Social Agent=] a [=Social Agent=] interacts with has a [=Social Agent Registration=].
A <dfn>Social Agent Registration</dfn> provides the [=Social Agent=]
with a place to track and manage other [=Social Agents=] they
interact with.
</p>

<p id=classApplicationRegistration>
Each [=Application=] a [=Social Agent=] interacts with has an [=Application Registration=].
An <dfn>Application Registration</dfn> provides the [=Social Agent=]
with a place to maintain metadata, state, preferences, and
other application-specific data associated with a given [=Application=] they
have elected to use.
</p>

ISSUE: Why do we need to distinguish between Social Agents and Applications on this level?

Both are stored in the [=Agent Registry=], as defined in the [[sai-am|Agent Management]] specification.
This document defines two additional predicates to distinguish 
between the different types of [=Agent Registrations=],
as specified in the table below.

<table class="classinfo data" align="left" id="classAgentRegistry">
  <colgroup></colgroup>
  <colgroup></colgroup>
  <colgroup></colgroup>
  <thead>
    <tr>
      <th>Property</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasSocialAgentRegistration</td>
      <td>[SocialAgentRegistration](#classSocialAgentRegistration)</td>
      <td>Link to an associated [=Social Agent Registration=] for 
      a given [=Social Agent=]</td>
    </tr>
    <tr>
      <td>hasApplicationRegistration</td>
      <td>[ApplicationRegistration](#classApplicationRegistration)</td>
      <td>Link to an associated [=Application Registration=] for 
      a given [=Application=]</td>
    </tr>
  </tbody>
</table>

<figure>
  <figcaption>An [=Agent Registry=] at https://alice.example/agents/ -
  <a href="snippets/alice.example/agents.ttl">View</a></figcaption>
  <pre class=include-code>
  path: snippets/alice.example/agents.ttl
  highlight: turtle
  show: 7-15
  </pre>
</figure>

The [=Agent Registry=] and its [=Agent Registrations=] 
are specified by the following definitions:

  - [=Agent Registry=]:
    [Class Definition](interop.ttl#AgentRegistry) -
    [Shape Definition](interop.shex#AgentRegistryShape) -
    [Shape Tree Definition](interop.tree#AgentRegistryTree)

  - [=Social Agent Registrations=]: 
    [Class Definition](interop.ttl#SocialAgentRegistration) -
    [Shape Definition](interop.shex#SocialAgentRegistrationShape) -
    [Shape Tree Definition](interop.tree#SocialAgentRegistrationTree)

  - [=Application Registrations=]: 
    [Class Definition](interop.ttl#ApplicationRegistration) -
    [Shape Definition](interop.shex#ApplicationRegistrationShape) -
    [Shape Tree Definition](interop.tree#ApplicationRegistrationTree)

<pre class=include>path: hierarchy.bs</pre>
