Social Agents {#social-agents}
=====================

A <dfn>Social Agent</dfn> is a strongly identifiable individual, group, or
organization that can own or be responsible for data, and provide authorization to the
access of that data by other [=Agents=].

Most of a [=Social Agent's=] information is stored in [=Registries=].

A <dfn>Registry</dfn> is a place where a [=Social Agent=] can store and find
different types of data, often for particular purposes. Each type
of [=Registry=] serves a specific purpose or function.

A [=Social Agent=] stores a list of its [=Registries=] in a [=Registry Set=],
which must be a separate resource from the [=identity profile document=]
that the [=Social Agent=] graph resides in so that it can be given more
restrictive (i.e. non-public) permissions.

The [=identity profile document=] <em class="rfc2119">MUST</em> 
be readable by the public. It <em class="rfc2119">MAY</em> 
use any resource or subject names.

Inboxes <em class="rfc2119">MUST</em> allow for other
[=Social Agents=] or [=Applications=] to create resources. Inboxes
<em class="rfc2119">SHOULD</em> limit the [=Social Agents=]
with create privileges to prevent denial of service, spam, or other
unwanted conditions.

[Class Definition](interop.ttl#SocialAgent) -
[Shape Definition](interop.shex#SocialAgentShape) -
[Shape Tree Definition](interop.tree#SocialAgentTree)

<table class="classinfo data" align="left" id="classSocialAgent">
  <colgroup></colgroup>
  <colgroup></colgroup>
  <colgroup></colgroup>
  <thead>
    <tr>
      <th>Property</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasRegistrySet</td>
      <td>[RegistrySet](#classRegistrySet)</td>
      <td>[=Registry Set=] for the [=Social Agent=]</td>
    </tr>
    <tr>
      <td>hasAuthorizationAgent</td>
      <td>[Application](#classApplication)</td>
      <td>The software used by the Agent to manage access to their data</td>
    </tr>
    <tr>
      <td>hasInbox</td>
      <td>ldp:inbox</td>
      <td>A general inbox for messages sent to the [=Social Agent=]</td>
    </tr>
    <tr>
      <td>hasAccessInbox</td>
      <td>ldp:inbox</td>
      <td>An inbox for access related messages sent to the [=Social Agent=]</td>
    </tr>
  </tbody>
</table>

<figure>
  <figcaption>[=Social Agent=] at https://alice.example/#id -
  <a href="snippets/alice.example/alice.example.ttl">View</a>
</figcaption>  
  <pre class=include-code>
  path: snippets/alice.example/alice.example.ttl
  highlight: turtle
  </pre> 
</figure>

## Registry Set ## {#datamodel-registry-set}

A <dfn>Registry Set</dfn> links to all of the [=Registries=] owned
by a given [=Social Agent=]. A non-public document, it is accessed by or
on behalf of the [=Social Agent=] or their [=Trusted Agents=] via trusted
[=Applications=].

The [=Registry Set=] <em class="rfc2119">MAY</em> use any resource or
subject names. It <em class="rfc2119">SHOULD NOT</em> be readable
by the public. It <em class="rfc2119">SHOULD</em> be accessible
and manageable by the [=Social Agent=] that owns it, or other
[=Social Agents=] that have received appropriate authorization, via
authorized [=Applications=].

[Class Definition](interop.ttl#RegistrySet) -
[Shape Definition](interop.shex#RegistrySetShape) -
[Shape Tree Definition](interop.tree#RegistrySetTree)

<table class="classinfo data" align="left" id="classRegistrySet">
  <colgroup></colgroup>
  <colgroup></colgroup>
  <colgroup></colgroup>
  <thead>
    <tr>
      <th>Property</th>
      <th>Range</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hasAgentRegistry</td>
      <td>[AgentRegistry](#classAgentRegistry)</td>
      <td>[=Agent Registry=] for the [=Social Agent=]</td>
    </tr>
    <tr>
      <td>hasAuthorizationRegistry</td>
      <td>[AuthorizationRegistry](#classAuthorizationRegistry)</td>
      <td>[=Authorization Registry=] for the [=Social Agent=]</td>
    </tr>
    <tr>
      <td>hasDataRegistry</td>
      <td>[DataRegistry](#classDataRegistry)</td>
      <td>[=Data Registry=] for the [=Social Agent=]</td>
    </tr>
  </tbody>
</table>

<figure>
  <figcaption>[=Registry Set=] at https://alice.example/registries -
  <a href="snippets/alice.example/registries.ttl">View</a>
  </figcaption>  
  <pre class=include-code>
  path: snippets/alice.example/registries.ttl
  highlight: turtle
  </pre> 
</figure>
