Trusted Agent {#trusted}
=====================

## Overview ## {#trusted-overview}

A <dfn>Trusted Agent</dfn> is...

## Data Model ## {#trusted-datamodel}

## Resource Hierarchy ## {#trusted-hierarchy}

## Permission Model ## {#trusted-permissions}

## Operations ## {#trusted-operations}

### Load Trusted Agent ### {#trusted-load}

Issue: Write operation for Load Trusted Agent

### Create Trusted Agent ### {#trusted-create}

Issue: Write operation for Create Trusted Agent

### Delete Trusted Agent ### {#trusted-delete}

Issue: Write operation for Delete Trusted Agent

### Redirect to Trusted Agent ### {#trusted-redirect}

Issue: Remove this and replace with routine for specific application service

### Return from Trusted Agent ### {#trusted-return}

Issue: Remove this and replace with routine for specific application service
