
### Discovery Request ### {#sec-amd-request}

[=Agents=] wishing to discover the [=Agent Manager=] for a given [=Entity=]
[SHOULD] dereference an [=HTTP-Dereferenceable Identifier=] of that [=Entity=],
e.g. `https://my.id/doc#me`.

    <div class=example id=ex-amd-request>

        Example [:GET:] request to an [=Entity=] [=Identifier=].
        
        <pre highlight=http>
            GET [L]https://my.id/profile#me[R] HTTP/1.1
        </pre>

    </div>
