Registering Agents {#ar}
=====================

The following operations pertain to
[Registering Agents](https://solid.github.io/data-interoperability-panel/specification/#ar)
in the [[SAI|Solid Application Interoperability Specification]].

##  Lookup Agent Registration ##  {#ar-lookup}

<table class="data operation" align="left">
  <colgroup></colgroup>
  <colgroup></colgroup>
  <thead>
    <tr><th colspan=2>Description</th></tr>
  </thead>
  <tbody>
    <tr>
      <td colspan=2>
        This operation returns an [=Agent Registration=] to an
        [=Agent=] with appropriate credentials to receive it.
      </td>
    </tr>
  </tbody>
  <thead>
    <tr><th colspan=2>Inputs</th></tr>
  </thead>
  <tbody>
    <tr>
      <td>`ID`</td>
      <td>URI [=identity=] of a given [=Social Agent=]</td>
    </tr>
  </tbody>
  <thead>
    <tr><th colspan=2>Outputs</th></tr>
  </thead>
  <tbody>
    <tr>
      <td>[=Agent Registration=]</td>
      <td>`AR` Matching the input `ID`</td>
    </tr>
  </tbody>
</table>

<div class="opdetails">

1. Let `AA` be the IRI object value of `interop:hasAuthorizationAgent` in 
    the graph returned by a `HEAD` or `GET` on `ID`
1. Send a `HEAD` or `GET` request to `AA`, authenticated as `ID`
1. Let `AR` be the IRI value of `anchor` in the `HTTP Link` header of the HTTP Response 
    with relation type `http://www.w3.org/ns/solid/interop#registeredAgent`, and 
    authenticated [=Social Agent's=] WebID as the link target.

</div>
